-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5116
  add constraint PK_NURTURESWOMEN_ID_5116 primary key (ID);
alter table NURTURESWOMEN_5116 add constraint FKNURTURESWOMENORG_5116 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5116 on NURTURESWOMEN_5116 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5116 on NURTURESWOMEN_5116 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5116 on NURTURESWOMEN_5116 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5116 on NURTURESWOMEN_5116 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5116 on NURTURESWOMEN_5116 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5101
  add constraint PK_NURTURESWOMEN_ID_5101 primary key (ID);
alter table NURTURESWOMEN_5101 add constraint FKNURTURESWOMENORG_5101 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5101 on NURTURESWOMEN_5101 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5101 on NURTURESWOMEN_5101 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5101 on NURTURESWOMEN_5101 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5101 on NURTURESWOMEN_5101 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5101 on NURTURESWOMEN_5101 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5103
  add constraint PK_NURTURESWOMEN_ID_5103 primary key (ID);
alter table NURTURESWOMEN_5103 add constraint FKNURTURESWOMENORG_5103 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5103 on NURTURESWOMEN_5103 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5103 on NURTURESWOMEN_5103 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5103 on NURTURESWOMEN_5103 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5103 on NURTURESWOMEN_5103 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5103 on NURTURESWOMEN_5103 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5104
  add constraint PK_NURTURESWOMEN_ID_5104 primary key (ID);
alter table NURTURESWOMEN_5104 add constraint FKNURTURESWOMENORG_5104 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5104 on NURTURESWOMEN_5104 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5104 on NURTURESWOMEN_5104 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5104 on NURTURESWOMEN_5104 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5104 on NURTURESWOMEN_5104 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5104 on NURTURESWOMEN_5104 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5105
  add constraint PK_NURTURESWOMEN_ID_5105 primary key (ID);
alter table NURTURESWOMEN_5105 add constraint FKNURTURESWOMENORG_5105 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5105 on NURTURESWOMEN_5105 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5105 on NURTURESWOMEN_5105 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5105 on NURTURESWOMEN_5105 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5105 on NURTURESWOMEN_5105 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5105 on NURTURESWOMEN_5105 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5106
  add constraint PK_NURTURESWOMEN_ID_5106 primary key (ID);
alter table NURTURESWOMEN_5106 add constraint FKNURTURESWOMENORG_5106 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5106 on NURTURESWOMEN_5106 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5106 on NURTURESWOMEN_5106 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5106 on NURTURESWOMEN_5106 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5106 on NURTURESWOMEN_5106 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5106 on NURTURESWOMEN_5106 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5107
  add constraint PK_NURTURESWOMEN_ID_5107 primary key (ID);
alter table NURTURESWOMEN_5107 add constraint FKNURTURESWOMENORG_5107 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5107 on NURTURESWOMEN_5107 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5107 on NURTURESWOMEN_5107 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5107 on NURTURESWOMEN_5107 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5107 on NURTURESWOMEN_5107 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5107 on NURTURESWOMEN_5107 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5108
  add constraint PK_NURTURESWOMEN_ID_5108 primary key (ID);
alter table NURTURESWOMEN_5108 add constraint FKNURTURESWOMENORG_5108 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5108 on NURTURESWOMEN_5108 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5108 on NURTURESWOMEN_5108 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5108 on NURTURESWOMEN_5108 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5108 on NURTURESWOMEN_5108 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5108 on NURTURESWOMEN_5108 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5109
  add constraint PK_NURTURESWOMEN_ID_5109 primary key (ID);
alter table NURTURESWOMEN_5109 add constraint FKNURTURESWOMENORG_5109 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5109 on NURTURESWOMEN_5109 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5109 on NURTURESWOMEN_5109 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5109 on NURTURESWOMEN_5109 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5109 on NURTURESWOMEN_5109 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5109 on NURTURESWOMEN_5109 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5110
  add constraint PK_NURTURESWOMEN_ID_5110 primary key (ID);
alter table NURTURESWOMEN_5110 add constraint FKNURTURESWOMENORG_5110 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5110 on NURTURESWOMEN_5110 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5110 on NURTURESWOMEN_5110 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5110 on NURTURESWOMEN_5110 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5110 on NURTURESWOMEN_5110 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5110 on NURTURESWOMEN_5110 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5111
  add constraint PK_NURTURESWOMEN_ID_5111 primary key (ID);
alter table NURTURESWOMEN_5111 add constraint FKNURTURESWOMENORG_5111 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5111 on NURTURESWOMEN_5111 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5111 on NURTURESWOMEN_5111 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5111 on NURTURESWOMEN_5111 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5111 on NURTURESWOMEN_5111 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5111 on NURTURESWOMEN_5111 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5113
  add constraint PK_NURTURESWOMEN_ID_5113 primary key (ID);
alter table NURTURESWOMEN_5113 add constraint FKNURTURESWOMENORG_5113 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5113 on NURTURESWOMEN_5113 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5113 on NURTURESWOMEN_5113 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5113 on NURTURESWOMEN_5113 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5113 on NURTURESWOMEN_5113 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5113 on NURTURESWOMEN_5113 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5114
  add constraint PK_NURTURESWOMEN_ID_5114 primary key (ID);
alter table NURTURESWOMEN_5114 add constraint FKNURTURESWOMENORG_5114 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5114 on NURTURESWOMEN_5114 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5114 on NURTURESWOMEN_5114 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5114 on NURTURESWOMEN_5114 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5114 on NURTURESWOMEN_5114 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5114 on NURTURESWOMEN_5114 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5115
  add constraint PK_NURTURESWOMEN_ID_5115 primary key (ID);
alter table NURTURESWOMEN_5115 add constraint FKNURTURESWOMENORG_5115 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5115 on NURTURESWOMEN_5115 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5115 on NURTURESWOMEN_5115 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5115 on NURTURESWOMEN_5115 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5115 on NURTURESWOMEN_5115 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5115 on NURTURESWOMEN_5115 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5117
  add constraint PK_NURTURESWOMEN_ID_5117 primary key (ID);
alter table NURTURESWOMEN_5117 add constraint FKNURTURESWOMENORG_5117 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5117 on NURTURESWOMEN_5117 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5117 on NURTURESWOMEN_5117 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5117 on NURTURESWOMEN_5117 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5117 on NURTURESWOMEN_5117 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5117 on NURTURESWOMEN_5117 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5118
  add constraint PK_NURTURESWOMEN_ID_5118 primary key (ID);
alter table NURTURESWOMEN_5118 add constraint FKNURTURESWOMENORG_5118 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5118 on NURTURESWOMEN_5118 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5118 on NURTURESWOMEN_5118 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5118 on NURTURESWOMEN_5118 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5118 on NURTURESWOMEN_5118 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5118 on NURTURESWOMEN_5118 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5119
  add constraint PK_NURTURESWOMEN_ID_5119 primary key (ID);
alter table NURTURESWOMEN_5119 add constraint FKNURTURESWOMENORG_5119 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5119 on NURTURESWOMEN_5119 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5119 on NURTURESWOMEN_5119 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5119 on NURTURESWOMEN_5119 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5119 on NURTURESWOMEN_5119 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5119 on NURTURESWOMEN_5119 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5120
  add constraint PK_NURTURESWOMEN_ID_5120 primary key (ID);
alter table NURTURESWOMEN_5120 add constraint FKNURTURESWOMENORG_5120 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5120 on NURTURESWOMEN_5120 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5120 on NURTURESWOMEN_5120 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5120 on NURTURESWOMEN_5120 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5120 on NURTURESWOMEN_5120 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5120 on NURTURESWOMEN_5120 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5132
  add constraint PK_NURTURESWOMEN_ID_5132 primary key (ID);
alter table NURTURESWOMEN_5132 add constraint FKNURTURESWOMENORG_5132 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5132 on NURTURESWOMEN_5132 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5132 on NURTURESWOMEN_5132 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5132 on NURTURESWOMEN_5132 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5132 on NURTURESWOMEN_5132 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5132 on NURTURESWOMEN_5132 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5133
  add constraint PK_NURTURESWOMEN_ID_5133 primary key (ID);
alter table NURTURESWOMEN_5133 add constraint FKNURTURESWOMENORG_5133 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5133 on NURTURESWOMEN_5133 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5133 on NURTURESWOMEN_5133 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5133 on NURTURESWOMEN_5133 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5133 on NURTURESWOMEN_5133 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5133 on NURTURESWOMEN_5133 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_5134
  add constraint PK_NURTURESWOMEN_ID_5134 primary key (ID);
alter table NURTURESWOMEN_5134 add constraint FKNURTURESWOMENORG_5134 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_5134 on NURTURESWOMEN_5134 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_5134 on NURTURESWOMEN_5134 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_5134 on NURTURESWOMEN_5134 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_5134 on NURTURESWOMEN_5134 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_5134 on NURTURESWOMEN_5134 (ORGID, BASEINFOID, ADDRESSINFOID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table nurtureswomen_3301
  add constraint PK_NURTURESWOMEN_ID_3301 primary key (ID);
alter table NURTURESWOMEN_3301 add constraint FKNURTURESWOMENORG_3301 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_NURTURESWOMEN_ADSID_3301 on NURTURESWOMEN_3301 (ADDRESSINFOID);
create index IDX_NUMEN_BASEINFOID_3301 on NURTURESWOMEN_3301 (BASEINFOID);
create index IDX_NU_ORGCODEANDISEMP_3301 on NURTURESWOMEN_3301 (ORGINTERNALCODE, ISEMPHASIS);
create index IND_NURTURESWOME_ORGID_3301 on NURTURESWOMEN_3301 (ORGID);
create index IND_NUTUWOM_OIDBIIDAID_3301 on NURTURESWOMEN_3301 (ORGID, BASEINFOID, ADDRESSINFOID);

