--数据管理数据迁移
--实有单位(国家行政机关)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '党政机关' AND p.internalid = 101),'PARTYGOVERNMENTORGANCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '国家行政机关' AND p.internalid = 10101),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype = (SELECT id FROM propertydicts p WHERE p.displayname='国家行政机关' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='实有企业_单位类别')));


--实有单位(政府)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '党政机关' AND p.internalid = 101),'PARTYGOVERNMENTORGANCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '政府' AND p.internalid = 10102),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype = (SELECT id FROM propertydicts p WHERE p.displayname='政府' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='实有企业_单位类别')));


--实有单位(国有企业)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 105),'OTHERCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 10507),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype = (SELECT id FROM propertydicts p WHERE p.displayname='国有企业' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='实有企业_单位类别')));


--实有单位(国有控股企业)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 105),'OTHERCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 10507),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype = (SELECT id FROM propertydicts p WHERE p.displayname='国有控股企业' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='实有企业_单位类别')));


--实有单位(外资企业)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 105),'OTHERCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 10507),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype = (SELECT id FROM propertydicts p WHERE p.displayname='外资企业' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='实有企业_单位类别')));


--实有单位(合资企业)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 105),'OTHERCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 10507),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype = (SELECT id FROM propertydicts p WHERE p.displayname='合资企业' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='实有企业_单位类别')));


--实有单位(私营企业)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 105),'OTHERCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 10507),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype = (SELECT id FROM propertydicts p WHERE p.displayname='私营企业' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='实有企业_单位类别')));


--实有单位(事业单位)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 105),'OTHERCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 10507),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype = (SELECT id FROM propertydicts p WHERE p.displayname='事业单位' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='实有企业_单位类别')));


--实有单位(类型不选择)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,address,type,classification,classificationen,category,username,telephone,faxnumber,area,remarks,businesslicenseno,orgcode,registeredcapitalno,begintime,endtime,generalstorage,countno,generalmanage,generalmente,economicnature,managementlevel,firelevel,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,haslicense,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,a.orgid,a.orginternalcode,a.name,a.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 105),'OTHERCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 10507),a.manager,a.telephone,a.fax,a.businessscope,a.remark,a.businesslicenseno,a.orgcode,a.registeredcapital,a.registrationdate,a.expirydate,a.registrationaddress,a.employeesnum,a.competentdepartment,a.supervisorydepartment,a.economicnature,a.supervisorylevel,a.firefightinglevel,a.claimstate,a.claimdate,a.claimusername,a.claimuserid,a.claimorgid,a.importdepartmentid,a.oldorgid,a.inid,a.dispose,a.claimavailable,a.importdate,a.districtorgid,CASE WHEN a.businesslicenseno is not null OR a.orgcode is not null THEN 1 ELSE 0 END,a.createuser,a.updateuser,a.createdate,a.updatedate from dm_actualcompany_temp a WHERE a.companytype is null);

--安全生产重点
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,faxnumber,coveredarea,remarks,haslicense,businesslicenseno,partycountnumber,registeredcapital,countno,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,scaletype,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 105),'OTHERCOMPANY',(SELECT id FROM  propertydicts p WHERE p.displayname = '单位-其他' AND p.internalid = 10507),s.manager,s.mobilenumber,s.telephone,s.fax,s.area,s.remark,CASE WHEN s.businesslicense is not null THEN 1 ELSE 0 END,s.businesslicense,s.partymemberamount,s.registeredcapital,s.employeeamount,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.type,s.createuser,s.updateuser,s.createdate,s.updatedate from dm_safetyproduct_temp s);


--消防安全重点(娱乐场所)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,f.orgid,f.orginternalcode,f.name,f.attentionextent,f.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '娱乐场所' AND p.internalid = 203),'ENTERTAINMENTPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '娱乐场所-其他' AND p.internalid = 20308),f.manager,f.mobilenumber,f.telephone,f.remark,f.claimstate,f.claimdate,f.claimusername,f.claimuserid,f.claimorgid,f.importdepartmentid,f.oldorgid,f.inid,f.dispose,f.claimavailable,f.importdate,f.districtorgid,f.createuser,f.updateuser,f.createdate,f.updatedate FROM dm_firesafetye_temp f where f.type = (SELECT id FROM propertydicts p WHERE p.displayname='娱乐场所' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='消防安全重点类别')));

--消防安全重点(商场)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,f.orgid,f.orginternalcode,f.name,f.attentionextent,f.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '商贸场所' AND p.internalid = 204),'TRADEPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '大型商场、超市' AND p.internalid = 20401),f.manager,f.mobilenumber,f.telephone,f.remark,f.claimstate,f.claimdate,f.claimusername,f.claimuserid,f.claimorgid,f.importdepartmentid,f.oldorgid,f.inid,f.dispose,f.claimavailable,f.importdate,f.districtorgid,f.createuser,f.updateuser,f.createdate,f.updatedate FROM dm_firesafetye_temp f where f.type = (SELECT id FROM propertydicts p WHERE p.displayname='商场' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='消防安全重点类别')));


--消防安全重点(市场)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,f.orgid,f.orginternalcode,f.name,f.attentionextent,f.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '商贸场所' AND p.internalid = 204),'TRADEPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '贸易市场' AND p.internalid = 20402),f.manager,f.mobilenumber,f.telephone,f.remark,f.claimstate,f.claimdate,f.claimusername,f.claimuserid,f.claimorgid,f.importdepartmentid,f.oldorgid,f.inid,f.dispose,f.claimavailable,f.importdate,f.districtorgid,f.createuser,f.updateuser,f.createdate,f.updatedate FROM dm_firesafetye_temp f where f.type = (SELECT id FROM propertydicts p WHERE p.displayname='市场' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='消防安全重点类别')));



--消防安全重点(重点单位)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,f.orgid,f.orginternalcode,f.name,f.attentionextent,f.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 21009),f.manager,f.mobilenumber,f.telephone,f.remark,f.claimstate,f.claimdate,f.claimusername,f.claimuserid,f.claimorgid,f.importdepartmentid,f.oldorgid,f.inid,f.dispose,f.claimavailable,f.importdate,f.districtorgid,f.createuser,f.updateuser,f.createdate,f.updatedate FROM dm_firesafetye_temp f where f.type = (SELECT id FROM propertydicts p WHERE p.displayname='重点单位' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='消防安全重点类别')));



--消防安全重点(其他)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,f.orgid,f.orginternalcode,f.name,f.attentionextent,f.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 21009),f.manager,f.mobilenumber,f.telephone,f.remark,f.claimstate,f.claimdate,f.claimusername,f.claimuserid,f.claimorgid,f.importdepartmentid,f.oldorgid,f.inid,f.dispose,f.claimavailable,f.importdate,f.districtorgid,f.createuser,f.updateuser,f.createdate,f.updatedate FROM dm_firesafetye_temp f where f.type = (SELECT id FROM propertydicts p WHERE p.displayname='其他' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='消防安全重点类别')));

--治安重点(车站码头)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '交通场所' AND p.internalid = 202),'TRAFFICPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '交通场所-其他' AND p.internalid = 20206),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='车站码头' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));


--治安重点(娱乐场所)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '娱乐场所' AND p.internalid = 203),'ENTERTAINMENTPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '娱乐场所-其他' AND p.internalid = 20308),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='娱乐场所' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));


--治安重点(批发市场)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '商贸场所' AND p.internalid = 204),'TRADEPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '贸易市场' AND p.internalid = 20402),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='批发市场' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));

--治安重点(宾馆与旅馆)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '住宿服务场所' AND p.internalid = 206),'ACCOMMODATIONSERVICESPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '宾馆、饭店（可住宿）' AND p.internalid = 20601),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='宾馆与旅馆' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));


--治安重点(城乡结合部)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '城乡结合部' AND p.internalid = 21004),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='城乡结合部' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));


--治安重点(城中村)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '城中村' AND p.internalid = 21005),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='城中村' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));


--治安重点(流动人口聚集地)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '流动人口聚集地' AND p.internalid = 21006),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='流动人口聚集地' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));


--治安重点(出租房屋区)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '出租房屋区' AND p.internalid = 21007),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='出租房屋区' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));


--治安重点(矿山市场)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '矿山市场' AND p.internalid = 21008),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='矿山市场' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));


--治安重点(其他)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 21009),s.manager,s.mobilenumber,s.telephone,s.remark,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate FROM dm_securitye_temp s where s.type = (SELECT id FROM propertydicts p WHERE p.displayname='其他' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='治安重点类别')));

--增加冗余新学校类型字段
ALTER TABLE dm_schools_temp ADD (newtype number(10));

update dm_schools_temp s set s.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '小学' AND p.internalid = 10201) WHERE s.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '小学' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='学校类型'));
update dm_schools_temp s set s.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '幼儿园' AND p.internalid = 10202) WHERE s.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '幼儿园' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='学校类型'));
update dm_schools_temp s set s.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '托管机构' AND p.internalid = 10203) WHERE s.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '托管机构' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='学校类型'));
update dm_schools_temp s set s.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '中学' AND p.internalid = 10204) WHERE s.type =(SELECT id FROM  propertydicts p WHERE p.displayname = '中学' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='学校类型'));
update dm_schools_temp s set s.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '大专院校' AND p.internalid = 10205) WHERE s.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '大专院校' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='学校类型'));
update dm_schools_temp s set s.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '成人教育、职高、技校等' AND p.internalid = 10206) WHERE s.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '职业学校' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='学校类型'));
update dm_schools_temp s set s.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '教育-其他' AND p.internalid = 10210) WHERE s.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '其它' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='学校类型'));


--学校
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,faxnumber,area,email,legalviceprincipal,schoolnature,schoolnameen,schoolwebsite,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,s.orgid,s.orginternalcode,s.name,s.attentionextent,s.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '学校' AND p.internalid = 102),'NEWSCHOOLS',s.newtype,s.manager,s.mobilenumber,s.telephone,s.fax,s.remark,s.email,s.vicepresident,s.kind,s.englishname,s.website,s.claimstate,s.claimdate,s.claimusername,s.claimuserid,s.claimorgid,s.importdepartmentid,s.oldorgid,s.inid,s.dispose,s.claimavailable,s.importdate,s.districtorgid,s.createuser,s.updateuser,s.createdate,s.updatedate from dm_schools_temp s);


--删除冗余新学校类型字段
ALTER TABLE dm_schools_temp DROP COLUMN newtype;

--增加冗余新医院类型字段
ALTER TABLE dm_hospitals_temp ADD (newtype number(10));

update dm_hospitals_temp h set h.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '综合医院' AND p.internalid = 10301) WHERE h.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '综合医院' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='医院类型'));
update dm_hospitals_temp h set h.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '专科医院' AND p.internalid = 10305) WHERE h.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '专科医院' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='医院类型'));
update dm_hospitals_temp h set h.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '门诊部、医务室、诊所' AND p.internalid = 10308) WHERE h.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '门诊' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='医院类型'));
update dm_hospitals_temp h set h.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '门诊部、医务室、诊所' AND p.internalid = 10308) WHERE h.type = (SELECT id FROM  propertydicts p WHERE p.displayname = '其他' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='医院类型'));
update dm_hospitals_temp h set h.newtype = (SELECT id FROM  propertydicts p WHERE p.displayname = '门诊部、医务室、诊所' AND p.internalid = 10308) WHERE h.type is null;

--医院
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,faxnumber,area,remarks,email,hospitalnature,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,h.orgid,h.orginternalcode,h.name,h.attentionextent,h.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '医院' AND p.internalid = 103),'NEWHOSPITAL',h.newtype,h.director,h.mobilenumber,h.telephone,h.fax,h.affiliatedunit,h.remark,h.email,h.kind,h.claimstate,h.claimdate,h.claimusername,h.claimuserid,h.claimorgid,h.importdepartmentid,h.oldorgid,h.inid,h.dispose,h.claimavailable,h.importdate,h.districtorgid,h.createuser,h.updateuser,h.createdate,h.updatedate from dm_hospitals_temp h);

--删除冗余新医院类型字段
ALTER TABLE dm_hospitals_temp DROP COLUMN newtype;


--危险化学品单位
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,telephone,area,remarks,generalstorage,generaltype,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,d.orgid,d.orginternalcode,d.name,d.attentionextent,d.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '危化品存放单位' AND p.internalid = 104),'NEWDANGEROUSCHEMICALSUNIT',(SELECT id FROM  propertydicts p WHERE p.displayname = '危险品存放站点' AND p.internalid = 10401),d.manager,d.telephone,d.copyscope,d.remark,d.storagedevice,d.commoditytype,d.claimstate,d.claimdate,d.claimusername,d.claimuserid,d.claimorgid,d.importdepartmentid,d.oldorgid,d.inid,d.dispose,d.claimavailable,d.importdate,d.districtorgid,d.createuser,d.updateuser,d.createdate,d.updatedate from dm_dangecunit_temp d);


--网吧
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,area,remarks,networkcardno,businessarea,generalstorage,generaltype,nowip,countno,generalmanage,generalmente,fireauditopinionno,internetbarno,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,i.orgid,i.orginternalcode,i.name,i.attentionextent,i.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '网吧' AND p.internalid = 205),'NEWINTERNETBAR',(SELECT id FROM  propertydicts p WHERE p.displayname = '网吧' AND p.internalid = 20501),i.manager,i.mobile,i.stationpolice,i.remark,i.tempnetcardnum,i.operationarea,i.internetaccesstype,i.netaccessproviders,i.useip,i.totalcomputernum,i.netculturelicenceno,i.netsecurityauditno,i.fireauditdocumentno,i.barcode,i.claimstate,i.claimdate,i.claimusername,i.claimuserid,i.claimorgid,i.importdepartmentid,i.oldorgid,i.inid,i.dispose,i.claimavailable,i.importdate,i.districtorgid,i.createuser,i.updateuser,i.createdate,i.updatedate from dm_internetbar_temp i);


--公共场所
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,area,coveredarea,remarks,cloakroom,businessarea,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,p.orgid,p.orginternalcode,p.name,p.attentionextent,p.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '商贸场所' AND p.internalid = 204),'TRADEPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '大型商场、超市' AND p.internalid = 20401),p.manager,p.passageway,p.totalarea,p.remark,p.cloakroom,p.operationarea,p.claimstate,p.claimdate,p.claimusername,p.claimuserid,p.claimorgid,p.importdepartmentid,p.oldorgid,p.inid,p.dispose,p.claimavailable,p.importdate,p.districtorgid,p.createuser,p.updateuser,p.createdate,p.updatedate from dm_publicplace_temp p);

--其他场所(餐饮服务)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '餐饮服务场所' AND p.internalid = 207),'NEWFOODSERVICESPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '餐饮服务场所-其他' AND p.internalid = 20707),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='餐饮服务' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));


--其他场所(个体诊所)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '医院' AND p.internalid = 103),'NEWHOSPITAL',(SELECT id FROM  propertydicts p WHERE p.displayname = '门诊部、医务室、诊所' AND p.internalid = 10308),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='个体诊所' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));


--其他场所(电镀)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '电镀站' AND p.internalid = 21002),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='电镀' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));

--其他场所(化妆品)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '化妆品' AND p.internalid = 21003),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='化妆品' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));

--其他场所(其他)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '场所' AND p.internalid = 2),(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 210),'OTHERPLACE',(SELECT id FROM  propertydicts p WHERE p.displayname = '场所-其他' AND p.internalid = 21009),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='其他' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));

--其他场所(药品)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '医院' AND p.internalid = 103),'NEWHOSPITAL',(SELECT id FROM  propertydicts p WHERE p.displayname = '药店、药房' AND p.internalid = 10315),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='药品' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));


--其他场所(医疗器械)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '医院' AND p.internalid = 103),'NEWHOSPITAL',(SELECT id FROM  propertydicts p WHERE p.displayname = '医疗器械' AND p.internalid = 10316),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='医疗器械' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));

--其他场所(煤气点)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '危化品存放单位' AND p.internalid = 104),'NEWDANGEROUSCHEMICALSUNIT',(SELECT id FROM  propertydicts p WHERE p.displayname = '天然气、煤气、液化气' AND p.internalid = 10403),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='煤气点' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));

--其他场所(加油站)
INSERT INTO dm_companyplace_temp(id,org,orginternalcode,name,attentionextent,address,type,classification,classificationen,category,username,mobilenumber,telephone,remarks,claimstate,claimdate,claimusername,claimuserid,claimorgid,importdepartmentid,oldorgid,inid,dispose,claimavailable,importdate,districtorgid,createuser,updateuser,createdate,updatedate)
(SELECT s_dm_companyplace_temp.nextval,o.orgid,o.orginternalcode,o.name,o.attentionextent,o.address,(SELECT id FROM  propertydicts p WHERE p.displayname = '单位' AND p.internalid = 1),(SELECT id FROM  propertydicts p WHERE p.displayname = '危化品存放单位' AND p.internalid = 104),'NEWDANGEROUSCHEMICALSUNIT',(SELECT id FROM  propertydicts p WHERE p.displayname = '油库' AND p.internalid = 10402),o.manager,o.mobilenumber,o.telephone,o.remark,o.claimstate,o.claimdate,o.claimusername,o.claimuserid,o.claimorgid,o.importdepartmentid,o.oldorgid,o.inid,o.dispose,o.claimavailable,o.importdate,o.districtorgid,o.createuser,o.updateuser,o.createdate,o.updatedate from dm_otherlocales_temp o where o.type = (SELECT id FROM propertydicts p WHERE p.displayname='加油站' AND p.propertydomainid = (SELECT id FROM propertydomains pd WHERE pd.domainname='其他场所类型')));
