/*研判分析登录统计和事件处理统计相关迁移合并脚本*/
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'issueDealStatReport', 1, 'issueCountHandler', 'ISSUECLASSIFICATIONSTAT', 'ORGID', 'ORGINTERNALCODE', 1, 0, 3, 1, '', '', '', '', 'admin', SYSDATE, '', SYSDATE);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'issueDealStatReport', 1, 'issueCountHandler', 'ISSUEHANDLESTAT', 'ORGID', 'ORGINTERNALCODE', 1, 0, 2, 1, '', '', '', '', 'admin', SYSDATE, '', SYSDATE);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'issueDealStatReport', 1, '', 'ISSUEANALYSIS', 'ORGID', 'ORGCODE', 0, 0, 1, 1, '', '', '', '', 'admin', SYSDATE, '', SYSDATE);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'orgLoginStanalsManage', 1, '', 'ORGLOGINSTANALS', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, '', '', '', '', 'admin', SYSDATE, '', SYSDATE);

commit;