--迁移合并业务配置：网格地图、地图区域
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_moduletable.nextval, 'gisLayerManage', 1, null, 'GIS2DLAYERS', 'ORGANIZATION', 'ORGINTERNALCODE', null, 0, 0, 1, 1, null, 'SELECT ID DATAID , ''''  EXPANSIONDATA,#ORGIDCOLUMN# DATAORGID FROM #TABLENAME#  WHERE #ORGIDCOLUMN# = #OLDORGID#', null, 'DELETE FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID# AND #OLDORGID# <>  #NEWORGID#', 'admin', sysdate, null, sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_moduletable.nextval, 'gisManagement', 1, null, 'HOURSEINFO', 'ORGID', 'ORGINTERNALCODE', null, 0, 0, 1, 1, null, null, null, null, 'admin', sysdate, null, sysdate);

commit;