insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceTeamMemberManagement', 1, '', 'SERVICETEAMMEMBERBASE', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'dustbinManagement', 1, '', 'DUSTBIN', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'skynetManagement', 1, '', 'SKYNET', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, '', '', '', 'delete #tableName# t1 where orgId = #oldOrgId#   and exists (select *  from #tableName# t2  where t2.orgId = #newOrgId#  and t1.code = t2.code)  and #oldOrgId# <> #newOrgId#', 'admin', sysdate, 'admin', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'basicLevelPartyManagement', 1, 'primaryOrganizationsHandler', 'PRIMARYORGANIZATIONS', 'ORGID', 'ORGINTERNALCODE', 1, 0, 1, 1, '', '', '', '', 'admin', sysdate, 'admin', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceRecordManagement', 1, '', 'SERVICERECORDS', 'ORGID', 'ORGCODE', 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceRecordManagement', 1, '', 'SERVICERECORDRELYOBJECT', 'ORGID', '', 0, 0, 2, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'bayonetManagement', 1, '', 'BAYONET', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, '', '', '', 'delete #tableName# t1 where orgId = #oldOrgId#   and exists (select *  from #tableName# t2  where t2.orgId = #newOrgId#  and t1.code = t2.code)  and #oldOrgId# <> #newOrgId#', 'admin', sysdate, 'admin', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'gridIntroductionManagement', 1, '', 'LEADERTEAMS', 'ORGID', 'ORGCODE', 0, 0, 2, 1, '', 'select id dataId,orgId dataOrgId,'' '' expansionData from #tableName# t where t.orgid=#oldOrgId#  and #oldOrgId# <> #newOrgId#', '', 'delete from #tableName# t where t.orgid=#oldOrgId#  and #oldOrgId# <> #newOrgId#', 'admin', sysdate, 'admin',sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceTeamManagement', 1, '', 'SERVICETEAMS', 'ORGID', 'ORGCODE', 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'gridIntroductionManagement', 1, '', 'VILLAGEPROFILES', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, '', 'select id dataId,orgId dataOrgId,'' '' expansionData from #tableName# t where t.orgid=#oldOrgId#  and #oldOrgId# <> #newOrgId#', '', 'delete from #tableName# t where t.orgid=#oldOrgId#  and #oldOrgId# <> #newOrgId#', 'admin', sysdate, 'admin',sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'snapshotSystemManagement', 1, '', 'SNAPSHOTSYSTEM', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, '', '', '', 'delete #tableName# t1 where orgId = #oldOrgId#   and exists (select *  from #tableName# t2  where t2.orgId = #newOrgId#  and t1.code = t2.code)  and #oldOrgId# <> #newOrgId#', 'admin', sysdate, 'admin',sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'newSocietyOrganizationsManagement', 1, 'newSocietyOrganizationsHandler', 'NEWSOCIETYORGANIZATIONS', 'ORGID', 'ORGINTERNALCODE', 1, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'newEconomicOrganizationsManagement', 1, 'newEconomicHandler', 'NEWECONOMICORGANIZATIONS', 'ORGID', 'ORGINTERNALCODE', 1, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'primaryMembersManagement', 1, 'primaryMembersHandler', 'PRIMARYMEMBERS', 'ORGID', 'ORGCODE', 1, 0, 1, 1, '', '', '', '', 'admin', sysdate, 'admin', sysdate);

commit;
