--迁移合并业务配置：十户联防
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_moduletable.nextval, 'receiveBoxCondition', 1, null, 'RECEIVEMSGINFO', 'ORGID', 'ORGCODE', null, 0, 0, 1, 1, null, null, null, null, 'admin', sysdate, null, sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_moduletable.nextval, 'sendBoxCondition', 1, null, 'SENDMSGINFO', 'ORGID', 'ORGCODE', null, 0, 0, 1, 1, null, null, null, null, 'admin', sysdate, null, sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_moduletable.nextval, 'familyCondition', 1, null, 'FAMILYINFO', 'ORGID', 'ORGINTERNALCODE', null, 0, 0, 1, 1, null, null, null, null, 'admin', sysdate, null, sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_moduletable.nextval, 'groupingCondition', 1, 'tenHouseholdsJointHandler', 'FAMILYTEAM', 'ORGID', 'ORGINTERNALCODE', null, 1, 0, 1, 1, null, null, null, null, 'admin', sysdate, null, sysdate);

commit;