-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5116
  add constraint PKHOUSEINFOS_5116 primary key (ID);
alter table HOUSEINFO_5116
  add constraint FKHOUSEINFOORG_5116 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5116 on HOUSEINFO_5116 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5116 on HOUSEINFO_5116 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5116 on HOUSEINFO_5116 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5116 on HOUSEINFO_5116 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5116 on HOUSEINFO_5116 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5116 on HOUSEINFO_5116 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5116 on HOUSEINFO_5116 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5101
  add constraint PKHOUSEINFOS_5101 primary key (ID);
alter table HOUSEINFO_5101
  add constraint FKHOUSEINFOORG_5101 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5101 on HOUSEINFO_5101 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5101 on HOUSEINFO_5101 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5101 on HOUSEINFO_5101 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5101 on HOUSEINFO_5101 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5101 on HOUSEINFO_5101 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5101 on HOUSEINFO_5101 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5101 on HOUSEINFO_5101 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5103
  add constraint PKHOUSEINFOS_5103 primary key (ID);
alter table HOUSEINFO_5103
  add constraint FKHOUSEINFOORG_5103 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5103 on HOUSEINFO_5103 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5103 on HOUSEINFO_5103 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5103 on HOUSEINFO_5103 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5103 on HOUSEINFO_5103 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5103 on HOUSEINFO_5103 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5103 on HOUSEINFO_5103 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5103 on HOUSEINFO_5103 (FEATUREID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5104
  add constraint PKHOUSEINFOS_5104 primary key (ID);
alter table HOUSEINFO_5104
  add constraint FKHOUSEINFOORG_5104 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5104 on HOUSEINFO_5104 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5104 on HOUSEINFO_5104 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5104 on HOUSEINFO_5104 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5104 on HOUSEINFO_5104 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5104 on HOUSEINFO_5104 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5104 on HOUSEINFO_5104 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5104 on HOUSEINFO_5104 (FEATUREID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5105
  add constraint PKHOUSEINFOS_5105 primary key (ID);
alter table HOUSEINFO_5105
  add constraint FKHOUSEINFOORG_5105 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5105 on HOUSEINFO_5105 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5105 on HOUSEINFO_5105 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5105 on HOUSEINFO_5105 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5105 on HOUSEINFO_5105 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5105 on HOUSEINFO_5105 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5105 on HOUSEINFO_5105 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5105 on HOUSEINFO_5105 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5106
  add constraint PKHOUSEINFOS_5106 primary key (ID);
alter table HOUSEINFO_5106
  add constraint FKHOUSEINFOORG_5106 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5106 on HOUSEINFO_5106 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5106 on HOUSEINFO_5106 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5106 on HOUSEINFO_5106 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5106 on HOUSEINFO_5106 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5106 on HOUSEINFO_5106 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5106 on HOUSEINFO_5106 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5106 on HOUSEINFO_5106 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5107
  add constraint PKHOUSEINFOS_5107 primary key (ID);
alter table HOUSEINFO_5107
  add constraint FKHOUSEINFOORG_5107 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5107 on HOUSEINFO_5107 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5107 on HOUSEINFO_5107 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5107 on HOUSEINFO_5107 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5107 on HOUSEINFO_5107 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5107 on HOUSEINFO_5107 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5107 on HOUSEINFO_5107 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5107 on HOUSEINFO_5107 (FEATUREID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5108
  add constraint PKHOUSEINFOS_5108 primary key (ID);
alter table HOUSEINFO_5108
  add constraint FKHOUSEINFOORG_5108 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5108 on HOUSEINFO_5108 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5108 on HOUSEINFO_5108 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5108 on HOUSEINFO_5108 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5108 on HOUSEINFO_5108 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5108 on HOUSEINFO_5108 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5108 on HOUSEINFO_5108 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5108 on HOUSEINFO_5108 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5109
  add constraint PKHOUSEINFOS_5109 primary key (ID);
alter table HOUSEINFO_5109
  add constraint FKHOUSEINFOORG_5109 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5109 on HOUSEINFO_5109 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5109 on HOUSEINFO_5109 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5109 on HOUSEINFO_5109 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5109 on HOUSEINFO_5109 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5109 on HOUSEINFO_5109 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5109 on HOUSEINFO_5109 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5109 on HOUSEINFO_5109 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5110
  add constraint PKHOUSEINFOS_5110 primary key (ID);
alter table HOUSEINFO_5110
  add constraint FKHOUSEINFOORG_5110 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5110 on HOUSEINFO_5110 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5110 on HOUSEINFO_5110 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5110 on HOUSEINFO_5110 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5110 on HOUSEINFO_5110 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5110 on HOUSEINFO_5110 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5110 on HOUSEINFO_5110 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5110 on HOUSEINFO_5110 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5111
  add constraint PKHOUSEINFOS_5111 primary key (ID);
alter table HOUSEINFO_5111
  add constraint FKHOUSEINFOORG_5111 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5111 on HOUSEINFO_5111 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5111 on HOUSEINFO_5111 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5111 on HOUSEINFO_5111 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5111 on HOUSEINFO_5111 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5111 on HOUSEINFO_5111 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5111 on HOUSEINFO_5111 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5111 on HOUSEINFO_5111 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5113
  add constraint PKHOUSEINFOS_5113 primary key (ID);
alter table HOUSEINFO_5113
  add constraint FKHOUSEINFOORG_5113 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5113 on HOUSEINFO_5113 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5113 on HOUSEINFO_5113 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5113 on HOUSEINFO_5113 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5113 on HOUSEINFO_5113 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5113 on HOUSEINFO_5113 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5113 on HOUSEINFO_5113 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5113 on HOUSEINFO_5113 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5114
  add constraint PKHOUSEINFOS_5114 primary key (ID);
alter table HOUSEINFO_5114
  add constraint FKHOUSEINFOORG_5114 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5114 on HOUSEINFO_5114 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5114 on HOUSEINFO_5114 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5114 on HOUSEINFO_5114 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5114 on HOUSEINFO_5114 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5114 on HOUSEINFO_5114 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5114 on HOUSEINFO_5114 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5114 on HOUSEINFO_5114 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5115
  add constraint PKHOUSEINFOS_5115 primary key (ID);
alter table HOUSEINFO_5115
  add constraint FKHOUSEINFOORG_5115 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5115 on HOUSEINFO_5115 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5115 on HOUSEINFO_5115 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5115 on HOUSEINFO_5115 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5115 on HOUSEINFO_5115 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5115 on HOUSEINFO_5115 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5115 on HOUSEINFO_5115 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5115 on HOUSEINFO_5115 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5117
  add constraint PKHOUSEINFOS_5117 primary key (ID);
alter table HOUSEINFO_5117
  add constraint FKHOUSEINFOORG_5117 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5117 on HOUSEINFO_5117 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5117 on HOUSEINFO_5117 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5117 on HOUSEINFO_5117 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5117 on HOUSEINFO_5117 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5117 on HOUSEINFO_5117 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5117 on HOUSEINFO_5117 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5117 on HOUSEINFO_5117 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5118
  add constraint PKHOUSEINFOS_5118 primary key (ID);
alter table HOUSEINFO_5118
  add constraint FKHOUSEINFOORG_5118 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5118 on HOUSEINFO_5118 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5118 on HOUSEINFO_5118 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5118 on HOUSEINFO_5118 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5118 on HOUSEINFO_5118 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5118 on HOUSEINFO_5118 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5118 on HOUSEINFO_5118 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5118 on HOUSEINFO_5118 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5119
  add constraint PKHOUSEINFOS_5119 primary key (ID);
alter table HOUSEINFO_5119
  add constraint FKHOUSEINFOORG_5119 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5119 on HOUSEINFO_5119 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5119 on HOUSEINFO_5119 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5119 on HOUSEINFO_5119 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5119 on HOUSEINFO_5119 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5119 on HOUSEINFO_5119 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5119 on HOUSEINFO_5119 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5119 on HOUSEINFO_5119 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5120
  add constraint PKHOUSEINFOS_5120 primary key (ID);
alter table HOUSEINFO_5120
  add constraint FKHOUSEINFOORG_5120 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5120 on HOUSEINFO_5120 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5120 on HOUSEINFO_5120 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5120 on HOUSEINFO_5120 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5120 on HOUSEINFO_5120 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5120 on HOUSEINFO_5120 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5120 on HOUSEINFO_5120 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5120 on HOUSEINFO_5120 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5132
  add constraint PKHOUSEINFOS_5132 primary key (ID);
alter table HOUSEINFO_5132
  add constraint FKHOUSEINFOORG_5132 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5132 on HOUSEINFO_5132 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5132 on HOUSEINFO_5132 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5132 on HOUSEINFO_5132 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5132 on HOUSEINFO_5132 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5132 on HOUSEINFO_5132 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5132 on HOUSEINFO_5132 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5132 on HOUSEINFO_5132 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5133
  add constraint PKHOUSEINFOS_5133 primary key (ID);
alter table HOUSEINFO_5133
  add constraint FKHOUSEINFOORG_5133 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5133 on HOUSEINFO_5133 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5133 on HOUSEINFO_5133 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5133 on HOUSEINFO_5133 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5133 on HOUSEINFO_5133 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5133 on HOUSEINFO_5133 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5133 on HOUSEINFO_5133 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5133 on HOUSEINFO_5133 (FEATUREID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_5134
  add constraint PKHOUSEINFOS_5134 primary key (ID);
alter table HOUSEINFO_5134
  add constraint FKHOUSEINFOORG_5134 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_5134 on HOUSEINFO_5134 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_5134 on HOUSEINFO_5134 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_5134 on HOUSEINFO_5134 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_5134 on HOUSEINFO_5134 (ADDRESS);
create index IND_HOUSEINFO_ORGID_5134 on HOUSEINFO_5134 (ORGID);
create index IND_HSEINFO_BDIDHUSE_5134 on HOUSEINFO_5134 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_5134 on HOUSEINFO_5134 (FEATUREID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEINFO_3301
  add constraint PKHOUSEINFOS_3301 primary key (ID);
alter table HOUSEINFO_3301
  add constraint FKHOUSEINFOORG_3301 foreign key (ORGID)
  references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index INDEXHIORGCODECREATEDATE_3301 on HOUSEINFO_3301 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHIHOUSECODEORGID_3301 on HOUSEINFO_3301 (HOUSECODE, ORGID);
create index INDEXHIORGINTERNALCODE_3301 on HOUSEINFO_3301 (ORGINTERNALCODE);
create index INDEXHOUSEINFOADDRESS_3301 on HOUSEINFO_3301 (ADDRESS);
create index IND_HOUSEINFO_ORGID_3301 on HOUSEINFO_3301 (ORGID);
create index IND_HSEINFO_BDIDHUSE_3301 on HOUSEINFO_3301 (BUILDDATASID, HOUSEUSES);
create index IND_HSEINFO_FTID_3301 on HOUSEINFO_3301 (FEATUREID);



create index HSEACTPOPLAT_HSEID on HOUSEHASACTUALPOPULATION (HOUSEID);
create index SHSEACTPOPLT_POPLATID on HOUSEHASACTUALPOPULATION (POPULATIONID);
create index IDX_POP_POPULATIONTYPE on HOUSEHASACTUALPOPULATION (POPULATIONID, POPULATIONTYPE);
create index IND_HUSHSACPOP_HIDPTYP on HOUSEHASACTUALPOPULATION (HOUSEID, POPULATIONTYPE);

