--单位场所基础临时表插入单位场所表
insert into companyplacebase(id,org,orginternalcode,name,attentionextent,address,isemphasis,isemphasisdate,isemphasisreason,centerlon,centerlat,centerlon2,centerlat2,featureid,builddataid,sourcesstate,pcormobile,imgurl,createuser,updateuser,createdate,updatedate)
(select c.id,c.org,c.orginternalcode,c.name,c.attentionextent,c.address,c.isemphasis,c.isemphasisdate,c.isemphasisreason,c.centerlon,c.centerlat,c.centerlon2,c.centerlat2,c.featureid,c.builddataid,c.sourcesstate,c.pcormobile,c.imgurl,c.createuser,c.updateuser,c.createdate,c.updatedate from companyplacebase_temp c);
--单位场所临时表插入单位场所表
insert into companyplace(id,baseid,type,classification,classificationen,category,username,mobilenumber,telephone,faxnumber,area,coveredarea,remarks,haslicense,businesslicenseno,orgcode,cloakroom,scaletype,partycountnumber,networkcardno,registeredcapital,registeredcapitalno,begintime,endtime,businessarea,digvolume,fillvolume,email,hospitalnature,generalstorage,generaltype,faxnno,nowip,countno,generalmanage,generalmente,fireauditopinionno,internetbarno,legalviceprincipal,schoolnature,schoolnameen,schoolwebsite,economicnature,managementlevel,firelevel,createuser,updateuser,createdate,updatedate)
(select cp.id,cp.baseid,cp.type,cp.classification,cp.classificationen,cp.category,cp.username,cp.mobilenumber,cp.telephone,cp.faxnumber,cp.area,cp.coveredarea,cp.remarks,cp.haslicense,cp.businesslicenseno,cp.orgcode,cp.cloakroom,cp.scaletype,cp.partycountnumber,cp.networkcardno,cp.registeredcapital,cp.registeredcapitalno,cp.begintime,cp.endtime,cp.businessarea,cp.digvolume,cp.fillvolume,cp.email,cp.hospitalnature,cp.generalstorage,cp.generaltype,cp.faxnno,cp.nowip,cp.countno,cp.generalmanage,cp.generalmente,cp.fireauditopinionno,cp.internetbarno,cp.legalviceprincipal,cp.schoolnature,cp.schoolnameen,cp.schoolwebsite,cp.economicnature,cp.managementlevel,cp.firelevel,cp.createuser,cp.updateuser,cp.createdate,cp.updatedate from companyplace_temp cp);
--单位场所业务临时表插入单位场所业务表
insert into companyplacebusiness(id,iskeytype,hiddangerinfo,correctioninfo,listedcorrection,listedleve,correctionbeigindate,correctionenddate,effectassessment,pollutiontype,pollutioninfo,createuser,updateuser,createdate,updatedate)
(select cb.id,cb.iskeytype,cb.hiddangerinfo,cb.correctioninfo,cb.listedcorrection,cb.listedleve,cb.correctionbeigindate,cb.correctionenddate,cb.effectassessment,cb.pollutiontype,cb.pollutioninfo,cb.createuser,cb.updateuser,cb.createdate,cb.updatedate from companyplacebusiness_temp cb);
--单位场所业务中间临时表插入单位场所中间表
insert into companyplacebusinessrelation(baseid,businessid)
(select cr.baseid,cr.businessid from companyplacebusslation_temp cr);