--出租屋表
insert into moduleTable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'rentalHouseManagement', 1, '', 'RENTALHOUSE', 'ORGID', 'ORGINTERNALCODE', 0, 0, 2, 1, 'select count(*) from rentalhouse where ORGID= #OLDORGID#', '', 'update rentalhouse  set ORGID=#NEWORGID# ,ORGINTERNALCODE=#NEWORGCODE# where  ORGID=#OLDORGID#', '', 'admin',sysdate, 'admin', sysdate);
--keyplace表
insert into moduleTable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'rentalHouseManagement', 1, '', 'KEYPLACES', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, 'select count(*) from keyplaces where orgId=#OLDORGID#', '', 'update keyplaces  set orgId=#NEWORGID# , ORGINTERNALCODE=#NEWORGCODE# where orgId=#OLDORGID#', '', 'admin', sysdate, 'admin', sysdate);

commit;