insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'userManagement', 1, '', 'USERS', 'ORGANIZATIONID', 'ORGINTERNALCODE', 0, 0, 1, 1, 'select count(*) from users where ORGANIZATIONID=#OLDORGID#', '', 'update users set ORGANIZATIONID=#NEWORGID# ,ORGINTERNALCODE=#NEWORGCODE# where ORGANIZATIONID=#OLDORGID#', '', 'admin', sysdate, 'admin', sysdate);

commit;