--楼宇布局表
insert into moduleTable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'builddatasManagement', 1, '', 'BUILDLAYOUT', 'ORGID', 'ORGINTERNALCODE', 0, 0, 1, 1, 'select count(*) from BUILDLAYOUT where BUILDID in(
			  select id from builddatas where ORGID=#OLDORGID# )', '', 'update BUILDLAYOUT  set ORGID=#NEWORGID# , ORGINTERNALCODE=#NEWORGCODE# where BUILDID in(
			  select id from builddatas where ORGID=#OLDORGID# )', '', 'admin',sysdate, 'admin', sysdate);
--楼宇信息表
insert into moduleTable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'builddatasManagement', 1, '', 'BUILDDATAS', 'ORGID', 'ORGINTERNALCODE', 0, 0, 2, 1, 'select count(*) from BUILDDATAS where ORGID=#OLDORGID#', '', 'update BUILDDATAS  set ORGID=#NEWORGID#, ORGINTERNALCODE=#NEWORGCODE# where ORGID=#OLDORGID#', '', 'admin', sysdate, 'admin', sysdate);

commit;