package com.tianque.solr.domain;

public enum DocumentType {
	ATTENTION_OBJECT, DRUGGY, DANGEROUS_GOODS_PRACTITIONER, RESIDENT, LETTING_HOUSE, SUPERIOR_VISIT, ENTERPRISEKEY, SCHOOL, HOSPITAL, RECTIFICATIVEPERSON, COMMON_COMPLEXPLACE, SPECIAL_TRADE, OTHER_LOCALE, POORPEOPLE, DANGER_TRAMP_RESIDENT, IDLE_YOUTH, AIDNEED_POPULATION, POSITIVE_INFO, MENTAL_PATIENT, PROTECTIONKEY, SAFETYPRODUCTIONKEY, FIRESAFETYKEY, SECURITYKEY, NEWSOCIETYFEDERATIONS, OVERSEAPERSONNEL, INHABITANT, INHABITANT_CONNECT, TRAMPRESIDENT, HANDICAPPED, SPEICALCAREGROUPS, ELDERLYPEOPLE, FLOATING_POPULATION, UNSETTLED_POPULATION, NURTURESWOMEN, DANGEROUSCHEMICALSUNIT, INTERNETBAR, PUBLICPLACE,PUBLICCOMPLEXPLACES, OTHERLOCALES, RENTALHOUSE, SCHOOLS, ENTERPRISEDOWNKEY, ACTUALCOMPANY, NEWECONOMICORGANIZATIONS, SCENICSPOTS, SCENICEQUIPMENT, SCENICTRAFFIC
}
