package com.tianque.excel.definition;

import com.tianque.baseInfo.companyPlace.constacts.ModulTypes;
import com.tianque.core.datatransfer.DataType;
import com.tianque.domain.property.PropertyTypes;

public class CompanyPlaceContext {
	public static String[][] getCompanyPlaceArray(String modulKey) {
		// 单位场所
		String[][] companyAndPlace = {
				{ "0", "", "规上规下企业清单", "", "", "true", "0", "44" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "通道口/所在派出所/所属单位/副本许可范围/经营范围", "", "", "true" },
				{ "15", "cloakRoom", "小件寄存处", "", "", "true" },
				{ "16", "coveredArea", "(总)面积", "", "", "true" },
				{ "17", "businessArea", "营业面积（平方米 ）", "", "", "true" },
				// 上网服务特有
				{ "18", "generalType", "宽带接入服务商", "", "", "true" },
				{ "19", "nowip", "现在使用IP", "", "", "true" },
				{ "20", "countNo", "电脑台数/从业人数", "", "", "true" },
				{ "21", "generalStorage", "接入方式/存储设备/注册地址", "", "", "true" },
				{ "22", "networkCardNo", "临时上网卡数", "", "", "true" },
				{ "23", "generalManage", "网络文化经营许可证号/主管部门", "", "", "true" },
				{ "24", "generalMente", "网络安全审核意见书号/管理部门", "", "", "true" },
				{ "25", "fireAuditOpinionNo", "消防审核意见书号", "", "", "true" },
				{ "26", "internetBarNo", "网吧编号", "", "", "true" },
				// 医疗卫生特有
				{ "27", "email", "电子邮件", "", "", "true" },
				{ "28", "hospitalNature", " 医院性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.HOSPITALS_KIND, "true" },
				// 危险品存放特有
				{ "29", "faxNo", "传真号码2", "", "", "true" },
				// 其他单位特有
				{ "30", "registeredCapitalNo", "注册资本", "", "", "true" },
				{ "31", "economicNature", "经济性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_ECONOMICNATURE, "true" },
				{ "32", "begintime", "注册开始时间", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "33", "endtime", "注册结束时间", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "34", "managementLevel", "管理等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.MANAGEMENT_LEVEL, "true" },
				{ "35", "fireLevel", "消防等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_FIREFIGHTINGLEVEL, "true" },
				// 公有
				{ "36", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "37", "partyCountNumber", "党员数", "", "", "true" },
				{ "38", "registeredCapital", "注册资金", "", "", "true" },
				{ "39", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "40", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "41", "orgCode", "组织机构码 ", "", "", "true" },
				{ "42", "remarks", "备注", "", "", "true" },
				{ "43", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "44", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };

		// 公共活动场所
		String[][] publicPlaceKey = {
				{ "0", "", "公共活动场所清单", "", "", "true", "0", "18" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "主管单位", "", "", "true" },
				{ "15", "coveredArea", "面积", "", "", "true" },
				{ "16", "remarks", "备注", "", "", "true" },
				{ "17", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "18", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" }

		};
		// 交通场所
		String[][] trafficPlaceKey = {
				{ "0", "", "交通场所清单", "", "", "true", "0", "18" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "主管单位", "", "", "true" },
				{ "15", "coveredArea", "面积", "", "", "true" },
				{ "16", "remarks", "备注", "", "", "true" },
				{ "17", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "18", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" }

		};
		// 娱乐场所
		String[][] entertainmentPlaceKey = {
				{ "0", "", "娱乐场所清单", "", "", "true", "0", "21" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "主管单位", "", "", "true" },
				{ "15", "coveredArea", "面积", "", "", "true" },
				{ "16", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "17", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "18", "orgCode", "组织机构码 ", "", "", "true" },
				{ "19", "remarks", "备注", "", "", "true" },
				{ "20", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "21", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 商贸场所
		String[][] tradePlaceKey = {
				{ "0", "", "商贸场所清单", "", "", "true", "0", "26" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "通道口", "", "", "true" },
				{ "15", "cloakRoom", "小件寄存处", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "16", "coveredArea", "总面积", "", "", "true" },
				{ "17", "businessArea", "营业面积（平方米 ）", "", "", "true" },
				{ "18", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "19", "partyCountNumber", "党员数", "", "", "true" },
				{ "20", "registeredCapital", "注册资金", "", "", "true" },
				{ "21", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "22", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "23", "orgCode", "组织机构码 ", "", "", "true" },
				{ "24", "remarks", "备注", "", "", "true" },
				{ "25", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "26", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" }

		};
		// 上网服务场所
		String[][] internetServicesPlaceKey = {
				{ "0", "", "网吧清单", "", "", "true", "0", "33" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "所在派出所", "", "", "true" },
				{ "15", "coveredArea", "面积", "", "", "true" },
				{ "16", "generalType", "宽带接入服务商", "", "", "true" },
				{ "17", "nowip", "现在使用IP", "", "", "true" },
				{ "18", "countNo", "电脑台数", "", "", "true" },
				{ "19", "generalStorage", "接入方式", "", "", "true" },
				{ "20", "networkCardNo", "临时上网卡数", "", "", "true" },
				{ "21", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "22", "partyCountNumber", "党员数", "", "", "true" },
				{ "23", "registeredCapital", "注册资金", "", "", "true" },
				{ "24", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "25", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "26", "orgCode", "组织机构码 ", "", "", "true" },
				{ "27", "generalManage", "网络文化经营许可证号", "", "", "true" },
				{ "28", "generalMente", "网络安全审核意见书号", "", "", "true" },
				{ "29", "fireAuditOpinionNo", "消防审核意见书号", "", "", "true" },
				{ "30", "internetBarNo", "网吧编号", "", "", "true" },
				{ "31", "remarks", "备注", "", "", "true" },
				{ "32", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "33", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" }

		};
		// 住宿服务场所
		String[][] accommodationServicesPlaceKey = {
				{ "0", "", "住宿服务场所清单", "", "", "true", "0", "19" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "15", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "16", "orgCode", "组织机构码 ", "", "", "true" },
				{ "17", "remarks", "备注", "", "", "true" },
				{ "18", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "19", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 餐饮服务场所
		String[][] foodServicesPlaceKey = {
				{ "0", "", "餐饮服务场所清单", "", "", "true", "0", "22" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "15", "partyCountNumber", "党员数", "", "", "true" },
				{ "16", "registeredCapital", "注册资金", "", "", "true" },
				{ "17", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "18", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "19", "orgCode", "组织机构码 ", "", "", "true" },
				{ "20", "remarks", "备注", "", "", "true" },
				{ "21", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "22", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" }

		};

		// 旅游场所
		String[][] travelingPlaceKey = {
				{ "0", "", "旅游场所清单", "", "", "true", "0", "16" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "remarks", "备注", "", "", "true" },
				{ "15", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "16", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 施工场所
		String[][] constructionPlaceKey = {
				{ "0", "", "施工场所清单", "", "", "true", "0", "22" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "施工单位", "", "", "true" },
				{ "15", "begintime", "开始时间（施工，注册）", DataType.DATA_TYPE_DATE,
						"", "true" },
				{ "16", "endtime", "结束时间（施工，注册）", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "17", "coveredArea", "施工面积", "", "", "true" },
				{ "18", "digVolume", "施工挖方量（立方米）", "", "", "true" },
				{ "19", "fillVolume", "施工填方量（立方米）", "", "", "true" },
				{ "20", "remarks", "备注", "", "", "true" },
				{ "21", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "22", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 其他场所
		String[][] otherPlaceKey = {
				{ "0", "", "其他场所清单", "", "", "true", "0", "22" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "15", "partyCountNumber", "党员数", "", "", "true" },
				{ "16", "registeredCapital", "注册资金", "", "", "true" },
				{ "17", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "18", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "19", "orgCode", "组织机构码 ", "", "", "true" },
				{ "20", "remarks", "备注", "", "", "true" },
				{ "21", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "22", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" }

		};

		// 党政机关
		String[][] partyGovernmentOrganCompanyKey = {
				{ "0", "", "党政机关清单", "", "", "true", "0", "14" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "telePhone", "联系电话", "", "", "true" },
				{ "11", "faxNumber", "传真号码", "", "", "true" },
				{ "12", "remarks", "备注", "", "", "true" },
				{ "13", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "14", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 教育
		String[][] educationCompanyKey = {
				{ "0", "", "学校清单", "", "", "true", "0", "25" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "校长", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "legalVicePrincipal", "法制副校长", "", "", "true" },
				{ "15", "schoolNature", "学校性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.SCHOOL_PROPERTY, "true" },
				{ "16", "schoolNameEn", "学校英文名称", "", "", "true" },
				{ "17", "email", "电子邮件", "", "", "true" },
				{ "18", "schoolWebSite", "学校网址", "", "", "true" },
				{ "19", "area", "周边情况", "", "", "true" },
				{ "20", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "21", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "22", "orgCode", "组织机构码 ", "", "", "true" },
				{ "23", "remarks", "备注", "", "", "true" },
				{ "24", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "25", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 医疗卫生
		String[][] medicalHygieneCompanyKey = {
				{ "0", "", "医院清单", "", "", "true", "0", "25" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "email", "电子邮件", "", "", "true" },
				{ "15", "hospitalNature", " 医院性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.HOSPITALS_KIND, "true" },
				{ "16", "area", "所属单位", "", "", "true" },
				{ "17", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "18", "partyCountNumber", "党员数", "", "", "true" },
				{ "19", "registeredCapital", "注册资金", "", "", "true" },
				{ "20", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "21", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "22", "orgCode", "组织机构码 ", "", "", "true" },
				{ "23", "remarks", "备注", "", "", "true" },
				{ "24", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "25", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 危险品存放单位
		String[][] dangerousStoreCompanyKey = {
				{ "0", "", "危险品存放单位清单", "", "", "true", "0", "25" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "generalStorage", "存储设备", "", "", "true" },
				{ "15", "area", "副本许可范围", "", "", "true" },
				{ "16", "faxNo", "传真号码2", "", "", "true" },
				{ "17", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "18", "partyCountNumber", "党员数", "", "", "true" },
				{ "19", "registeredCapital", "注册资金", "", "", "true" },
				{ "20", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "21", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "22", "orgCode", "组织机构码 ", "", "", "true" },
				{ "23", "remarks", "备注", "", "", "true" },
				{ "24", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "25", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 其他单位
		String[][] otherCompanyKey = {
				{ "0", "", "其他单位清单", "", "", "true", "0", "33" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "registeredCapitalNo", "注册资本", "", "", "true" },
				{ "15", "economicNature", "经济性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_ECONOMICNATURE, "true" },
				{ "16", "begintime", "注册开始时间", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "17", "endtime", "注册结束时间", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "18", "area", "经营范围", "", "", "true" },
				{ "19", "generalStorage", "注册地址", "", "", "true" },
				{ "20", "countNo", "从业人数", "", "", "true" },
				{ "21", "generalManage", "主管部门", "", "", "true" },
				{ "22", "managementLevel", "管理等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.MANAGEMENT_LEVEL, "true" },
				{ "23", "generalMente", "管理部门", "", "", "true" },
				{ "24", "fireLevel", "消防等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_FIREFIGHTINGLEVEL, "true" },
				{ "25", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "26", "partyCountNumber", "党员数", "", "", "true" },
				{ "27", "registeredCapital", "注册资金", "", "", "true" },
				{ "28", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "29", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "30", "orgCode", "组织机构码 ", "", "", "true" },
				{ "31", "remarks", "备注", "", "", "true" },
				{ "32", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "33", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 安全生产重点
		String[][] safetyProductionKeyKey = {
				{ "0", "", "安全生产重点清单", "", "", "true", "0", "17" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "5", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "6", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "7", "userName", "负责人（校长，法人等）", "", "", "true" },
				{ "8", "mobileNumber", "联系手机", "", "", "true" },
				{ "9", "telePhone", "联系电话", "", "", "true" },
				{ "10", "faxNumber", "传真号码", "", "", "true" },
				{ "11", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "12", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "13", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "14", "orgCode", "组织机构码 ", "", "", "true" },
				{ "15", "remarks", "备注", "", "", "true" },
				{ "16", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "17", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 消防安全重点
		String[][] fireSafetyKey = {
				{ "0", "", "消防安全重点清单", "", "", "true", "0", "17" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "5", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "6", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "7", "userName", "负责人（校长，法人等）", "", "", "true" },
				{ "8", "mobileNumber", "联系手机", "", "", "true" },
				{ "9", "telePhone", "联系电话", "", "", "true" },
				{ "10", "faxNumber", "传真号码", "", "", "true" },
				{ "11", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "12", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "13", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "14", "orgCode", "组织机构码 ", "", "", "true" },
				{ "15", "remarks", "备注", "", "", "true" },
				{ "16", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "17", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 治安重点
		String[][] securityKey = {
				{ "0", "", "治安重点清单", "", "", "true", "0", "17" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "5", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "6", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "7", "userName", "负责人（校长，法人等）", "", "", "true" },
				{ "8", "mobileNumber", "联系手机", "", "", "true" },
				{ "9", "telePhone", "联系电话", "", "", "true" },
				{ "10", "faxNumber", "传真号码", "", "", "true" },
				{ "11", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "12", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "13", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "14", "orgCode", "组织机构码 ", "", "", "true" },
				{ "15", "remarks", "备注", "", "", "true" },
				{ "16", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "17", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 污染源
		String[][] pollutionSource = {
				{ "0", "", "污染源清单", "", "", "true", "0", "17" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "5", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "6", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "7", "userName", "负责人（校长，法人等）", "", "", "true" },
				{ "8", "mobileNumber", "联系手机", "", "", "true" },
				{ "9", "telePhone", "联系电话", "", "", "true" },
				{ "10", "faxNumber", "传真号码", "", "", "true" },
				{ "11", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "12", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "13", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "14", "orgCode", "组织机构码 ", "", "", "true" },
				{ "15", "remarks", "备注", "", "", "true" },
				{ "16", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "17", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };
		// 规上规下企业
		String[][] enterpriseKey = {
				{ "0", "", "规上企业清单", "", "", "true", "0", "44" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "通道口/所在派出所/所属单位/副本许可范围/经营范围", "", "", "true" },
				{ "15", "cloakRoom", "小件寄存处", "", "", "true" },
				{ "16", "coveredArea", "(总)面积", "", "", "true" },
				{ "17", "businessArea", "营业面积（平方米 ）", "", "", "true" },
				// 上网服务特有
				{ "18", "generalType", "宽带接入服务商", "", "", "true" },
				{ "19", "nowip", "现在使用IP", "", "", "true" },
				{ "20", "countNo", "电脑台数/从业人数", "", "", "true" },
				{ "21", "generalStorage", "接入方式/存储设备/注册地址", "", "", "true" },
				{ "22", "networkCardNo", "临时上网卡数", "", "", "true" },
				{ "23", "generalManage", "网络文化经营许可证号/主管部门", "", "", "true" },
				{ "24", "generalMente", "网络安全审核意见书号/管理部门", "", "", "true" },
				{ "25", "fireAuditOpinionNo", "消防审核意见书号", "", "", "true" },
				{ "26", "internetBarNo", "网吧编号", "", "", "true" },
				// 医疗卫生特有
				{ "27", "email", "电子邮件", "", "", "true" },
				{ "28", "hospitalNature", " 医院性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.HOSPITALS_KIND, "true" },
				// 危险品存放特有
				{ "29", "faxNo", "传真号码2", "", "", "true" },
				// 其他单位特有
				{ "30", "registeredCapitalNo", "注册资本", "", "", "true" },
				{ "31", "economicNature", "经济性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_ECONOMICNATURE, "true" },
				{ "32", "begintime", "注册开始时间", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "33", "endtime", "注册结束时间", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "34", "managementLevel", "管理等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.MANAGEMENT_LEVEL, "true" },
				{ "35", "fireLevel", "消防等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_FIREFIGHTINGLEVEL, "true" },
				// 公有
				{ "36", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "37", "partyCountNumber", "党员数", "", "", "true" },
				{ "38", "registeredCapital", "注册资金", "", "", "true" },
				{ "39", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "40", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "41", "orgCode", "组织机构码 ", "", "", "true" },
				{ "42", "remarks", "备注", "", "", "true" },
				{ "43", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "44", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" }

		};
		String[][] enterpriseDownKey = {
				{ "0", "", "规下企业清单", "", "", "true", "0", "44" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "通道口/所在派出所/所属单位/副本许可范围/经营范围", "", "", "true" },
				{ "15", "cloakRoom", "小件寄存处", "", "", "true" },
				{ "16", "coveredArea", "(总)面积", "", "", "true" },
				{ "17", "businessArea", "营业面积（平方米 ）", "", "", "true" },
				// 上网服务特有
				{ "18", "generalType", "宽带接入服务商", "", "", "true" },
				{ "19", "nowip", "现在使用IP", "", "", "true" },
				{ "20", "countNo", "电脑台数/从业人数", "", "", "true" },
				{ "21", "generalStorage", "接入方式/存储设备/注册地址", "", "", "true" },
				{ "22", "networkCardNo", "临时上网卡数", "", "", "true" },
				{ "23", "generalManage", "网络文化经营许可证号/主管部门", "", "", "true" },
				{ "24", "generalMente", "网络安全审核意见书号/管理部门", "", "", "true" },
				{ "25", "fireAuditOpinionNo", "消防审核意见书号", "", "", "true" },
				{ "26", "internetBarNo", "网吧编号", "", "", "true" },
				// 医疗卫生特有
				{ "27", "email", "电子邮件", "", "", "true" },
				{ "28", "hospitalNature", " 医院性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.HOSPITALS_KIND, "true" },
				// 危险品存放特有
				{ "29", "faxNo", "传真号码2", "", "", "true" },
				// 其他单位特有
				{ "30", "registeredCapitalNo", "注册资本", "", "", "true" },
				{ "31", "economicNature", "经济性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_ECONOMICNATURE, "true" },
				{ "32", "begintime", "注册开始时间", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "33", "endtime", "注册结束时间", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "34", "managementLevel", "管理等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.MANAGEMENT_LEVEL, "true" },
				{ "35", "fireLevel", "消防等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_FIREFIGHTINGLEVEL, "true" },
				// 公有
				{ "36", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "37", "partyCountNumber", "党员数", "", "", "true" },
				{ "38", "registeredCapital", "注册资金", "", "", "true" },
				{ "39", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "40", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "41", "orgCode", "组织机构码 ", "", "", "true" },
				{ "42", "remarks", "备注", "", "", "true" },
				{ "43", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "44", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" }

		};

		String[][] commonArray1 = {
				{ "0", "", "单位场所清单", "", "", "true", "0", "48" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "isEmphasis", "是否取消关注", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "5", "isEmphasisDate", "取消关注日期", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "6", "isEmphasisReason", "取消关注原因", "", "", "true" },
				{ "7", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "8", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "9", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "10", "userName", "负责人（校长，法人等）", "", "", "true" },
				{ "11", "mobileNumber", "联系手机", "", "", "true" },
				{ "12", "telePhone", "联系电话", "", "", "true" },
				{ "13", "faxNumber", "传真号码", "", "", "true" },
				{ "14", "area", "所在区域", "", "", "true" },
				{ "15", "coveredArea", "面积", "", "", "true" },
				{ "16", "remarks", "备注", "", "", "true" },
				{ "17", "hasLicense", "是否有证照", "", "", "true" },
				{ "18", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "19", "orgCode", "组织机构码 ", "", "", "true" },
				{ "20", "cloakRoom", "小件寄存处", "", "", "true" },
				{ "21", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "22", "networkCardNo", "临时上网卡数", "", "", "true" },
				{ "23", "registeredCapital", "注册资金", "", "", "true" },
				{ "24", "begintime", "开始时间（施工，注册）", DataType.DATA_TYPE_DATE,
						"", "true" },
				{ "25", "endtime", "结束时间（施工，注册）", DataType.DATA_TYPE_DATE, "",
						"true" },
				{ "26", "businessArea", "营业面积（平方米 ）", "", "", "true" },
				{ "27", "digVolume", "施工挖方量（立方米）", "", "", "true" },
				{ "28", "fillVolume", "施工填方量（立方米）", "", "", "true" },
				{ "29", "email", "电子邮件", "", "", "true" },
				{ "30", "hospitalNature", " 医院性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.HOSPITALS_KIND, "true" },
				{ "31", "generalStorage", "存储设备/注册地址/接入方式", "", "", "true" },
				{ "32", "generalType", "货物类别/宽带接入方式", "", "", "true" },
				{ "33", "faxNo", "传真号码2", "", "", "true" },
				{ "34", "nowip", "现在使用IP", "", "", "true" },
				{ "35", "countNo", "电脑台数/从业人数", "", "", "true" },
				{ "36", "generalManage", "网络文化经营许可证号/主管部门", "", "", "true" },
				{ "37", "generalMente", "网络安全审核意见书号/管理部门", "", "", "true" },
				{ "38", "fireAuditOpinionNo", "消防审核意见书号", "", "", "true" },
				{ "39", "internetBarNo", "网吧编号", "", "", "true" },
				{ "40", "legalVicePrincipal", "法制副校长", "", "", "true" },
				{ "41", "schoolNature", "学校性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.SCHOOL_PROPERTY, "true" },
				{ "42", "schoolNameEn", "学校英文名称", "", "", "true" },
				{ "43", "schoolWebSite", "学校网址", "", "", "true" },
				{ "44", "economicNature", "经济性质", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_ECONOMICNATURE, "true" },
				{ "45", "managementLevel", "管理等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.MANAGEMENT_LEVEL, "true" },
				{ "46", "fireLevel", "消防等级", DataType.DATA_TYPE_DICT,
						PropertyTypes.ACTUALCOMPANY_FIREFIGHTINGLEVEL, "true" },
				{ "47", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "48", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };

		// 目前决定导出的公共字段
		// 所属网格、名称、关注程度、地址、类型（3级），负责人、联系手机。联系固话，传真号码，规模（规上规下）、是否有证照，营业执照号，组织机构代码、备注
		String[][] commonArray = {
				{ "0", "", "单位场所清单", "", "", "true", "0", "17" },
				{ "0", "name", "单位场所名称", "", "", "true" },
				{ "1", "org", "所属网格", DataType.DATA_TYPE_ORG, "", "true" },
				{ "2", "attentionextent", "关注度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "3", "address", "地址", "", "", "true" },
				{ "4", "type", "单位/场所", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_TYPE, "true" },
				{ "5", "classifiCation", "分类", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CLASSIFICATION, "true" },
				{ "6", "category", "类别", DataType.DATA_TYPE_DICT,
						PropertyTypes.COMPANY_PLACE_CATEGORY, "true" },
				{ "7", "userName", "负责人（校长，法人等）", "", "", "true" },
				{ "8", "mobileNumber", "联系手机", "", "", "true" },
				{ "9", "telePhone", "联系电话", "", "", "true" },
				{ "10", "faxNumber", "传真号码", "", "", "true" },
				{ "11", "scaleType", "规模类型（规上，规下 ）", DataType.DATA_TYPE_DICT,
						PropertyTypes.ENTERPRISE_TYPE, "true" },
				{ "12", "hasLicense", "是否有证照", DataType.DATA_TYPE_BOOLEAN, "",
						"true" },
				{ "13", "businessLicenseNo", "营业执照号码 ", "", "", "true" },
				{ "14", "orgCode", "组织机构码 ", "", "", "true" },
				{ "15", "remarks", "备注", "", "", "true" },
				{ "16", "hasServiceTeamMember", "有无治安负责人",
						DataType.DATA_TYPE_LONG, "", "true" },
				{ "17", "lastRecordTime", "最新巡场记录", DataType.DATA_TYPE_DATE,
						"", "true" } };

		if (modulKey.equals(ModulTypes.PUBLICPLACE_KEY)) {
			return publicPlaceKey;
		}
		if (modulKey.equals(ModulTypes.TRAFFICPLACE_KEY)) {
			return trafficPlaceKey;
		}
		if (modulKey.equals(ModulTypes.ENTERTAINMENTPLACE_KEY)) {
			return entertainmentPlaceKey;
		}
		if (modulKey.equals(ModulTypes.TRADEPLACE_KEY)) {
			return tradePlaceKey;
		}
		if (modulKey.equals(ModulTypes.INTERNETSERVICESPLACE_KEY)) {
			return internetServicesPlaceKey;
		}
		if (modulKey.equals(ModulTypes.ACCOMMODATIONSERVICESPLACE_KEY)) {
			return accommodationServicesPlaceKey;
		}
		if (modulKey.equals(ModulTypes.FOODSERVICESPLACE_KEY)) {
			return foodServicesPlaceKey;
		}
		if (modulKey.equals(ModulTypes.OTHERPLACE_KEY)) {
			return otherPlaceKey;
		}
		if (modulKey.equals(ModulTypes.TRAVELINGPLACE_KEY)) {
			return travelingPlaceKey;
		}
		if (modulKey.equals(ModulTypes.CONSTRUCTIONPLACE_KEY)) {
			return constructionPlaceKey;
		}
		if (modulKey.equals(ModulTypes.PARTYGOVERNMENTORGANCOMPANY_KEY)) {
			return partyGovernmentOrganCompanyKey;
		}
		if (modulKey.equals(ModulTypes.EDUCATIONCOMPANY_KEY)) {
			return educationCompanyKey;
		}
		if (modulKey.equals(ModulTypes.MEDICALHYGIENECOMPANY_KEY)) {
			return medicalHygieneCompanyKey;
		}
		if (modulKey.equals(ModulTypes.DANGEROUSSTORECOMPANY_KEY)) {
			return dangerousStoreCompanyKey;
		}
		if (modulKey.equals(ModulTypes.OTHERCOMPANY_KEY)) {
			return otherCompanyKey;
		}
		// 重点

		if (modulKey.equals(ModulTypes.SAFETYPRODUCTIONKEY_KEY)) {
			return safetyProductionKeyKey;
		}
		if (modulKey.equals(ModulTypes.FIRESAFETYKEY_KEY)) {
			return fireSafetyKey;
		}
		if (modulKey.equals(ModulTypes.SECURITYKEY_KEY)) {
			return securityKey;
		}
		if (modulKey.equals(ModulTypes.POLLUTIONSOURCE_KEY)) {
			return pollutionSource;
		}

		if (modulKey.equals(ModulTypes.ENTERPRISE_KEY)) {
			return enterpriseKey;
		}
		if (modulKey.equals(ModulTypes.ENTERPRISEDOWN_KEY)) {
			return enterpriseDownKey;
		}
		return commonArray;
	}
}
