
--TBSchedule日志序列新增
CREATE SEQUENCE S_TBSCHEDULELOG
MINVALUE 1
MAXVALUE 9999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE SEQUENCE S_TBSCHEDULELOGEXCEPTION
MINVALUE 1
MAXVALUE 9999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

--任务调度日志表
CREATE TABLE TBSCHEDULELOG  (
   ID                 NUMBER(10)                      NOT NULL,
   JOBNAME            VARCHAR2(4000),
   TASKPARAMETER      VARCHAR2(4000),
   OWNSIGN            VARCHAR2(40),
   TASKITEMNUM        NUMBER(6),
   TASKITEMS          VARCHAR2(2000),
   EACHFETCHDATANUM   NUMBER(10),
   STARTTIME          DATE,
   ENDTIME            DATE,
   REMARK             VARCHAR2(4000),
   APPNAME            VARCHAR2(40),
   LISTSIZE           NUMBER(10),
   EXCEPTIONNUM       NUMBER(10),
   CONSTRAINT PK_TBSCHEDULELOG PRIMARY KEY (ID)
);

--任务调度异常信息表
CREATE TABLE TBSCHEDULELOGEXCEPTION
(
  ID        NUMBER(10) NOT NULL,
  LOGID       NUMBER(10) NOT NULL,
  ERRORMSG  VARCHAR2(4000) NOT NULL,
  ERRORTIME DATE NOT NULL,
   CONSTRAINT PK_TBSCHEDULELOGEXCEPTION PRIMARY KEY (ID)
);
-- 外键关联
ALTER TABLE TBSCHEDULELOGEXCEPTION
  ADD CONSTRAINT FK_TBSCHEDULELOG_EXCEPTION FOREIGN KEY (LOGID)
  REFERENCES TBSCHEDULELOG (ID);
  
--不合法身份证表
CREATE TABLE IdCardNoExpLog(
  expMessage  VARCHAR2(4000) NOT NULL,
  expIdCardNo  varchar2(20) NOT NULL
);

create index IdCardNoExpLog_idCardNo on IdCardNoExpLog(expIdCardNo);
