--考核评估-越级规则
insert into moduletable (ID, ENAME, ACTIVE, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE, BEANNAME)
values (s_MODULETABLE.NEXTVAL, 'issueSkipruleManagement', 1, 'ISSUE_SKIPRULE', 'ORG_ID', 'ORG_INTERNAL_CODE', 0, 0, 1, 1, 'SELECT COUNT(*) FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'SELECT ID DATAID ,''''   expansionData ,#ORGIDCOLUMN# DATAORGID FROM #TABLENAME#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'UPDATE #TABLENAME# SET #ORGIDCOLUMN#=#NEWORGID#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'DELETE FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID# AND #OLDORGID# <>  #NEWORGID#', 'admin', sysdate, 'admin',sysdate, '');
--职能部门时限标准
insert into moduletable (ID, ENAME, ACTIVE, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE, BEANNAME)
values (s_MODULETABLE.NEXTVAL, 'functionOrgTimeLimitStandardManagement', 1, 'ISSUESTANDARDFORFUNORG', 'ORGID', 'ORGID', 0, 0, 1, 1, 'SELECT COUNT(*) FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'SELECT ID DATAID , ''''  expansionData,#ORGIDCOLUMN# DATAORGID FROM #TABLENAME#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'UPDATE #TABLENAME# SET #ORGIDCOLUMN#=#NEWORGID# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'DELETE FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID# AND #OLDORGID# <>  #NEWORGID#', 'admin', sysdate, 'admin', sysdate, '');
--职能部门时限标准
insert into moduletable (ID, ENAME, ACTIVE, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE, BEANNAME)
values (s_MODULETABLE.NEXTVAL, 'administrativeOrgTimeLimitStandardManagement', 1, 'ADMINISTRATIVESTANDARD', 'CREATEORG', 'CREATEORG', 0, 0, 1, 1, 'SELECT COUNT(*) FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'SELECT ID DATAID , ''''  expansionData,#ORGIDCOLUMN# DATAORGID FROM #TABLENAME#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'UPDATE #TABLENAME# SET #ORGIDCOLUMN#=#NEWORGID# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'DELETE FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID# AND #OLDORGID# <>  #NEWORGID#', 'admin', sysdate, 'admin', sysdate, '');
--日常监督
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'SUPERVISIONADMINISTRATION', 'ORGID', 'ORGCODE', 0, 0, 2, 1, 'SELECT COUNT(*) FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'SELECT ID DATAID , ''''  EXPANSIONDATA,#ORGIDCOLUMN# DATAORGID FROM #TABLENAME#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'UPDATE #TABLENAME# SET #ORGIDCOLUMN#=#NEWORGID#,#ORGCODECOLUMN#=#NEWORGCODE# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'DELETE FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID# AND #OLDORGID# <>  #NEWORGID#', 'csz@', sysdate, 'admin', sysdate);
--社区平安和谐
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, 'peaceVillageHander', 'PEACE_VILLAGE', 'ORG_ID', 'ORG_INTERNAL_CODE', 1, 0, 3, 1, 'SELECT COUNT(*) FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'SELECT ID DATAID , ''''  EXPANSIONDATA,#ORGIDCOLUMN# DATAORGID FROM #TABLENAME#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'UPDATE #TABLENAME# SET #ORGIDCOLUMN#=#NEWORGID#,#ORGCODECOLUMN#=#NEWORGCODE#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'DELETE FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID# AND #OLDORGID# <>  #NEWORGID#', 'csz@', sysdate, 'admin', sysdate);
--社区以上的平安和谐
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, 'pacificUnionFoundingHander', 'PEACE_HIGH_VILLAGE', 'ORGID', 'ORGINTERNALCODE', 1, 0, 4, 1, 'SELECT COUNT(*) FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID#', 'SELECT ID DATAID , ''''  EXPANSIONDATA,#ORGIDCOLUMN# DATAORGID FROM #TABLENAME#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'UPDATE #TABLENAME# SET #ORGIDCOLUMN#=#NEWORGID#,#ORGCODECOLUMN#=#NEWORGCODE#  WHERE #ORGIDCOLUMN# = #OLDORGID#', 'DELETE FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID# AND #OLDORGID# <>  #NEWORGID#', 'admin', sysdate, 'admin', sysdate);
--延期申请
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUEAPPLYDELAY', 'AUDITORG', 'AUDITORG', 0, 0, 5, 1, 'SELECT COUNT(*) FROM #TABLENAME# WHERE #ORGIDCOLUMN# = #OLDORGID#', '', 'UPDATE #TABLENAME# SET #ORGIDCOLUMN#=#NEWORGID# WHERE #ORGIDCOLUMN# = #OLDORGID#', '', 'admin', sysdate, 'admin', sysdate);
--事件历史表
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUES_HISTORY', 'OCCURORG', 'OCCURORGINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUES_HISTORY', 'CREATEORG', 'CREATEORGINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, 'admin', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUES_HISTORY', 'LASTORG', 'LASTORGINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUESTEPS_HISTORY', 'SOURCE', 'SOURCEINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, 'admin', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUESTEPS_HISTORY', 'TARGET', 'TARGETINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, 'admin', sysdate);
--已办结的数据
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'COMPLETEDISSUE', 'CREATEORG', 'CREATEORGINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

--事件处理
insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUES', 'OCCURORG', 'OCCURORGINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUES', 'CREATEORG', 'CREATEORGINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, 'admin', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUES', 'LASTORG', 'LASTORGINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, '', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUESTEPS', 'SOURCE', 'SOURCEINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, 'admin', sysdate);

insert into moduletable (ID, ENAME, ACTIVE, BEANNAME, TABLENAME, ORGIDCOLUMN, ORGCODECOLUMN, SPLIT, EXECUTETYPE, ISMAINTABLE, EXECUTELEVEL, OPERATEMODE, COUNTSCRIPT, SELECTSCRIPT, UPDATESCRIPT, DELETESCRIPT, CREATEUSER, CREATEDATE, UPDATEUSER, UPDATEDATE)
values (s_MODULETABLE.NEXTVAL, 'serviceWork', 1, '', 'ISSUESTEPS', 'TARGET', 'TARGETINTERNALCODE', null, 0, 0, 1, 1, '', '', '', '', 'admin', sysdate, 'admin', sysdate);

commit;

