-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5116
  add constraint PK_HOUSEHOLAFFS_ID_5116 primary key (ID);
alter table HOUSEHOLDSTAFFS_5116
  add constraint FK_CENSUS_FAMILYID_5116 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5116 add constraint FK_ORGANIZATIONS_ORGID_5116 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5116 on HOUSEHOLDSTAFFS_5116 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5116 on HOUSEHOLDSTAFFS_5116 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5116 on HOUSEHOLDSTAFFS_5116 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5116 on HOUSEHOLDSTAFFS_5116 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5116 on HOUSEHOLDSTAFFS_5116 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5116 on HOUSEHOLDSTAFFS_5116 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5116 on HOUSEHOLDSTAFFS_5116 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5116 on HOUSEHOLDSTAFFS_5116 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5116 on HOUSEHOLDSTAFFS_5116 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5116 on HOUSEHOLDSTAFFS_5116 (ORGID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5101
  add constraint PK_HOUSEHOLAFFS_ID_5101 primary key (ID);
alter table HOUSEHOLDSTAFFS_5101
  add constraint FK_CENSUS_FAMILYID_5101 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5101 add constraint FK_ORGANIZATIONS_ORGID_5101 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5101 on HOUSEHOLDSTAFFS_5101 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5101 on HOUSEHOLDSTAFFS_5101 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5101 on HOUSEHOLDSTAFFS_5101 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5101 on HOUSEHOLDSTAFFS_5101 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5101 on HOUSEHOLDSTAFFS_5101 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5101 on HOUSEHOLDSTAFFS_5101 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5101 on HOUSEHOLDSTAFFS_5101 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5101 on HOUSEHOLDSTAFFS_5101 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5101 on HOUSEHOLDSTAFFS_5101 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5101 on HOUSEHOLDSTAFFS_5101 (ORGID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5103
  add constraint PK_HOUSEHOLAFFS_ID_5103 primary key (ID);
alter table HOUSEHOLDSTAFFS_5103
  add constraint FK_CENSUS_FAMILYID_5103 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5103 add constraint FK_ORGANIZATIONS_ORGID_5103 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5103 on HOUSEHOLDSTAFFS_5103 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5103 on HOUSEHOLDSTAFFS_5103 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5103 on HOUSEHOLDSTAFFS_5103 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5103 on HOUSEHOLDSTAFFS_5103 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5103 on HOUSEHOLDSTAFFS_5103 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5103 on HOUSEHOLDSTAFFS_5103 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5103 on HOUSEHOLDSTAFFS_5103 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5103 on HOUSEHOLDSTAFFS_5103 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5103 on HOUSEHOLDSTAFFS_5103 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5103 on HOUSEHOLDSTAFFS_5103 (ORGID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5104
  add constraint PK_HOUSEHOLAFFS_ID_5104 primary key (ID);
alter table HOUSEHOLDSTAFFS_5104
  add constraint FK_CENSUS_FAMILYID_5104 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5104 add constraint FK_ORGANIZATIONS_ORGID_5104 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5104 on HOUSEHOLDSTAFFS_5104 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5104 on HOUSEHOLDSTAFFS_5104 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5104 on HOUSEHOLDSTAFFS_5104 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5104 on HOUSEHOLDSTAFFS_5104 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5104 on HOUSEHOLDSTAFFS_5104 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5104 on HOUSEHOLDSTAFFS_5104 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5104 on HOUSEHOLDSTAFFS_5104 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5104 on HOUSEHOLDSTAFFS_5104 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5104 on HOUSEHOLDSTAFFS_5104 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5104 on HOUSEHOLDSTAFFS_5104 (ORGID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5105
  add constraint PK_HOUSEHOLAFFS_ID_5105 primary key (ID);
alter table HOUSEHOLDSTAFFS_5105
  add constraint FK_CENSUS_FAMILYID_5105 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5105 add constraint FK_ORGANIZATIONS_ORGID_5105 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5105 on HOUSEHOLDSTAFFS_5105 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5105 on HOUSEHOLDSTAFFS_5105 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5105 on HOUSEHOLDSTAFFS_5105 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5105 on HOUSEHOLDSTAFFS_5105 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5105 on HOUSEHOLDSTAFFS_5105 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5105 on HOUSEHOLDSTAFFS_5105 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5105 on HOUSEHOLDSTAFFS_5105 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5105 on HOUSEHOLDSTAFFS_5105 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5105 on HOUSEHOLDSTAFFS_5105 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5105 on HOUSEHOLDSTAFFS_5105 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5106
  add constraint PK_HOUSEHOLAFFS_ID_5106 primary key (ID);
alter table HOUSEHOLDSTAFFS_5106
  add constraint FK_CENSUS_FAMILYID_5106 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5106 add constraint FK_ORGANIZATIONS_ORGID_5106 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5106 on HOUSEHOLDSTAFFS_5106 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5106 on HOUSEHOLDSTAFFS_5106 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5106 on HOUSEHOLDSTAFFS_5106 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5106 on HOUSEHOLDSTAFFS_5106 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5106 on HOUSEHOLDSTAFFS_5106 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5106 on HOUSEHOLDSTAFFS_5106 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5106 on HOUSEHOLDSTAFFS_5106 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5106 on HOUSEHOLDSTAFFS_5106 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5106 on HOUSEHOLDSTAFFS_5106 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5106 on HOUSEHOLDSTAFFS_5106 (ORGID);



-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5107
  add constraint PK_HOUSEHOLAFFS_ID_5107 primary key (ID);
alter table HOUSEHOLDSTAFFS_5107
  add constraint FK_CENSUS_FAMILYID_5107 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5107 add constraint FK_ORGANIZATIONS_ORGID_5107 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5107 on HOUSEHOLDSTAFFS_5107 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5107 on HOUSEHOLDSTAFFS_5107 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5107 on HOUSEHOLDSTAFFS_5107 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5107 on HOUSEHOLDSTAFFS_5107 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5107 on HOUSEHOLDSTAFFS_5107 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5107 on HOUSEHOLDSTAFFS_5107 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5107 on HOUSEHOLDSTAFFS_5107 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5107 on HOUSEHOLDSTAFFS_5107 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5107 on HOUSEHOLDSTAFFS_5107 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5107 on HOUSEHOLDSTAFFS_5107 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5108
  add constraint PK_HOUSEHOLAFFS_ID_5108 primary key (ID);
alter table HOUSEHOLDSTAFFS_5108
  add constraint FK_CENSUS_FAMILYID_5108 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5108 add constraint FK_ORGANIZATIONS_ORGID_5108 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5108 on HOUSEHOLDSTAFFS_5108 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5108 on HOUSEHOLDSTAFFS_5108 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5108 on HOUSEHOLDSTAFFS_5108 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5108 on HOUSEHOLDSTAFFS_5108 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5108 on HOUSEHOLDSTAFFS_5108 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5108 on HOUSEHOLDSTAFFS_5108 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5108 on HOUSEHOLDSTAFFS_5108 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5108 on HOUSEHOLDSTAFFS_5108 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5108 on HOUSEHOLDSTAFFS_5108 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5108 on HOUSEHOLDSTAFFS_5108 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5109
  add constraint PK_HOUSEHOLAFFS_ID_5109 primary key (ID);
alter table HOUSEHOLDSTAFFS_5109
  add constraint FK_CENSUS_FAMILYID_5109 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5109 add constraint FK_ORGANIZATIONS_ORGID_5109 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5109 on HOUSEHOLDSTAFFS_5109 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5109 on HOUSEHOLDSTAFFS_5109 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5109 on HOUSEHOLDSTAFFS_5109 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5109 on HOUSEHOLDSTAFFS_5109 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5109 on HOUSEHOLDSTAFFS_5109 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5109 on HOUSEHOLDSTAFFS_5109 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5109 on HOUSEHOLDSTAFFS_5109 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5109 on HOUSEHOLDSTAFFS_5109 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5109 on HOUSEHOLDSTAFFS_5109 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5109 on HOUSEHOLDSTAFFS_5109 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5110
  add constraint PK_HOUSEHOLAFFS_ID_5110 primary key (ID);
alter table HOUSEHOLDSTAFFS_5110
  add constraint FK_CENSUS_FAMILYID_5110 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5110 add constraint FK_ORGANIZATIONS_ORGID_5110 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5110 on HOUSEHOLDSTAFFS_5110 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5110 on HOUSEHOLDSTAFFS_5110 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5110 on HOUSEHOLDSTAFFS_5110 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5110 on HOUSEHOLDSTAFFS_5110 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5110 on HOUSEHOLDSTAFFS_5110 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5110 on HOUSEHOLDSTAFFS_5110 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5110 on HOUSEHOLDSTAFFS_5110 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5110 on HOUSEHOLDSTAFFS_5110 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5110 on HOUSEHOLDSTAFFS_5110 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5110 on HOUSEHOLDSTAFFS_5110 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5111
  add constraint PK_HOUSEHOLAFFS_ID_5111 primary key (ID);
alter table HOUSEHOLDSTAFFS_5111
  add constraint FK_CENSUS_FAMILYID_5111 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5111 add constraint FK_ORGANIZATIONS_ORGID_5111 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5111 on HOUSEHOLDSTAFFS_5111 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5111 on HOUSEHOLDSTAFFS_5111 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5111 on HOUSEHOLDSTAFFS_5111 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5111 on HOUSEHOLDSTAFFS_5111 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5111 on HOUSEHOLDSTAFFS_5111 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5111 on HOUSEHOLDSTAFFS_5111 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5111 on HOUSEHOLDSTAFFS_5111 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5111 on HOUSEHOLDSTAFFS_5111 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5111 on HOUSEHOLDSTAFFS_5111 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5111 on HOUSEHOLDSTAFFS_5111 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5113
  add constraint PK_HOUSEHOLAFFS_ID_5113 primary key (ID);
alter table HOUSEHOLDSTAFFS_5113
  add constraint FK_CENSUS_FAMILYID_5113 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5113 add constraint FK_ORGANIZATIONS_ORGID_5113 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5113 on HOUSEHOLDSTAFFS_5113 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5113 on HOUSEHOLDSTAFFS_5113 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5113 on HOUSEHOLDSTAFFS_5113 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5113 on HOUSEHOLDSTAFFS_5113 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5113 on HOUSEHOLDSTAFFS_5113 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5113 on HOUSEHOLDSTAFFS_5113 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5113 on HOUSEHOLDSTAFFS_5113 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5113 on HOUSEHOLDSTAFFS_5113 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5113 on HOUSEHOLDSTAFFS_5113 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5113 on HOUSEHOLDSTAFFS_5113 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5114
  add constraint PK_HOUSEHOLAFFS_ID_5114 primary key (ID);
alter table HOUSEHOLDSTAFFS_5114
  add constraint FK_CENSUS_FAMILYID_5114 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5114 add constraint FK_ORGANIZATIONS_ORGID_5114 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5114 on HOUSEHOLDSTAFFS_5114 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5114 on HOUSEHOLDSTAFFS_5114 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5114 on HOUSEHOLDSTAFFS_5114 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5114 on HOUSEHOLDSTAFFS_5114 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5114 on HOUSEHOLDSTAFFS_5114 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5114 on HOUSEHOLDSTAFFS_5114 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5114 on HOUSEHOLDSTAFFS_5114 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5114 on HOUSEHOLDSTAFFS_5114 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5114 on HOUSEHOLDSTAFFS_5114 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5114 on HOUSEHOLDSTAFFS_5114 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5115
  add constraint PK_HOUSEHOLAFFS_ID_5115 primary key (ID);
alter table HOUSEHOLDSTAFFS_5115
  add constraint FK_CENSUS_FAMILYID_5115 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5115 add constraint FK_ORGANIZATIONS_ORGID_5115 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5115 on HOUSEHOLDSTAFFS_5115 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5115 on HOUSEHOLDSTAFFS_5115 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5115 on HOUSEHOLDSTAFFS_5115 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5115 on HOUSEHOLDSTAFFS_5115 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5115 on HOUSEHOLDSTAFFS_5115 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5115 on HOUSEHOLDSTAFFS_5115 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5115 on HOUSEHOLDSTAFFS_5115 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5115 on HOUSEHOLDSTAFFS_5115 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5115 on HOUSEHOLDSTAFFS_5115 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5115 on HOUSEHOLDSTAFFS_5115 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5117
  add constraint PK_HOUSEHOLAFFS_ID_5117 primary key (ID);
alter table HOUSEHOLDSTAFFS_5117
  add constraint FK_CENSUS_FAMILYID_5117 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5117 add constraint FK_ORGANIZATIONS_ORGID_5117 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5117 on HOUSEHOLDSTAFFS_5117 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5117 on HOUSEHOLDSTAFFS_5117 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5117 on HOUSEHOLDSTAFFS_5117 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5117 on HOUSEHOLDSTAFFS_5117 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5117 on HOUSEHOLDSTAFFS_5117 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5117 on HOUSEHOLDSTAFFS_5117 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5117 on HOUSEHOLDSTAFFS_5117 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5117 on HOUSEHOLDSTAFFS_5117 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5117 on HOUSEHOLDSTAFFS_5117 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5117 on HOUSEHOLDSTAFFS_5117 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5118
  add constraint PK_HOUSEHOLAFFS_ID_5118 primary key (ID);
alter table HOUSEHOLDSTAFFS_5118
  add constraint FK_CENSUS_FAMILYID_5118 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5118 add constraint FK_ORGANIZATIONS_ORGID_5118 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5118 on HOUSEHOLDSTAFFS_5118 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5118 on HOUSEHOLDSTAFFS_5118 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5118 on HOUSEHOLDSTAFFS_5118 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5118 on HOUSEHOLDSTAFFS_5118 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5118 on HOUSEHOLDSTAFFS_5118 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5118 on HOUSEHOLDSTAFFS_5118 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5118 on HOUSEHOLDSTAFFS_5118 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5118 on HOUSEHOLDSTAFFS_5118 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5118 on HOUSEHOLDSTAFFS_5118 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5118 on HOUSEHOLDSTAFFS_5118 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5119
  add constraint PK_HOUSEHOLAFFS_ID_5119 primary key (ID);
alter table HOUSEHOLDSTAFFS_5119
  add constraint FK_CENSUS_FAMILYID_5119 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5119 add constraint FK_ORGANIZATIONS_ORGID_5119 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5119 on HOUSEHOLDSTAFFS_5119 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5119 on HOUSEHOLDSTAFFS_5119 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5119 on HOUSEHOLDSTAFFS_5119 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5119 on HOUSEHOLDSTAFFS_5119 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5119 on HOUSEHOLDSTAFFS_5119 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5119 on HOUSEHOLDSTAFFS_5119 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5119 on HOUSEHOLDSTAFFS_5119 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5119 on HOUSEHOLDSTAFFS_5119 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5119 on HOUSEHOLDSTAFFS_5119 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5119 on HOUSEHOLDSTAFFS_5119 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5120
  add constraint PK_HOUSEHOLAFFS_ID_5120 primary key (ID);
alter table HOUSEHOLDSTAFFS_5120
  add constraint FK_CENSUS_FAMILYID_5120 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5120 add constraint FK_ORGANIZATIONS_ORGID_5120 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5120 on HOUSEHOLDSTAFFS_5120 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5120 on HOUSEHOLDSTAFFS_5120 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5120 on HOUSEHOLDSTAFFS_5120 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5120 on HOUSEHOLDSTAFFS_5120 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5120 on HOUSEHOLDSTAFFS_5120 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5120 on HOUSEHOLDSTAFFS_5120 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5120 on HOUSEHOLDSTAFFS_5120 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5120 on HOUSEHOLDSTAFFS_5120 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5120 on HOUSEHOLDSTAFFS_5120 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5120 on HOUSEHOLDSTAFFS_5120 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5132
  add constraint PK_HOUSEHOLAFFS_ID_5132 primary key (ID);
alter table HOUSEHOLDSTAFFS_5132
  add constraint FK_CENSUS_FAMILYID_5132 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5132 add constraint FK_ORGANIZATIONS_ORGID_5132 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5132 on HOUSEHOLDSTAFFS_5132 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5132 on HOUSEHOLDSTAFFS_5132 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5132 on HOUSEHOLDSTAFFS_5132 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5132 on HOUSEHOLDSTAFFS_5132 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5132 on HOUSEHOLDSTAFFS_5132 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5132 on HOUSEHOLDSTAFFS_5132 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5132 on HOUSEHOLDSTAFFS_5132 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5132 on HOUSEHOLDSTAFFS_5132 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5132 on HOUSEHOLDSTAFFS_5132 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5132 on HOUSEHOLDSTAFFS_5132 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5133
  add constraint PK_HOUSEHOLAFFS_ID_5133 primary key (ID);
alter table HOUSEHOLDSTAFFS_5133
  add constraint FK_CENSUS_FAMILYID_5133 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5133 add constraint FK_ORGANIZATIONS_ORGID_5133 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5133 on HOUSEHOLDSTAFFS_5133 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5133 on HOUSEHOLDSTAFFS_5133 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5133 on HOUSEHOLDSTAFFS_5133 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5133 on HOUSEHOLDSTAFFS_5133 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5133 on HOUSEHOLDSTAFFS_5133 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5133 on HOUSEHOLDSTAFFS_5133 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5133 on HOUSEHOLDSTAFFS_5133 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5133 on HOUSEHOLDSTAFFS_5133 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5133 on HOUSEHOLDSTAFFS_5133 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5133 on HOUSEHOLDSTAFFS_5133 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_5134
  add constraint PK_HOUSEHOLAFFS_ID_5134 primary key (ID);
alter table HOUSEHOLDSTAFFS_5134
  add constraint FK_CENSUS_FAMILYID_5134 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_5134 add constraint FK_ORGANIZATIONS_ORGID_5134 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_5134 on HOUSEHOLDSTAFFS_5134 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_5134 on HOUSEHOLDSTAFFS_5134 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_5134 on HOUSEHOLDSTAFFS_5134 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_5134 on HOUSEHOLDSTAFFS_5134 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_5134 on HOUSEHOLDSTAFFS_5134 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_5134 on HOUSEHOLDSTAFFS_5134 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_5134 on HOUSEHOLDSTAFFS_5134 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_5134 on HOUSEHOLDSTAFFS_5134 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_5134 on HOUSEHOLDSTAFFS_5134 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_5134 on HOUSEHOLDSTAFFS_5134 (ORGID);


-- Create/Recreate primary, unique and foreign key constraints 
alter table HOUSEHOLDSTAFFS_3301
  add constraint PK_HOUSEHOLAFFS_ID_3301 primary key (ID);
alter table HOUSEHOLDSTAFFS_3301
  add constraint FK_CENSUS_FAMILYID_3301 foreign key (FAMILYID)
  references CENSUSREGISTERFAMILYS (ID);
alter table HOUSEHOLDSTAFFS_3301 add constraint FK_ORGANIZATIONS_ORGID_3301 foreign key (ORGID) references ORGANIZATIONS (ID);
-- Create/Recreate indexes 
create index IDX_HOLD_ADSID_3301 on HOUSEHOLDSTAFFS_3301 (ADDRESSINFOID);
create index IDX_HOLD_BASEINFOID_3301 on HOUSEHOLDSTAFFS_3301 (BASEINFOID);
create index IDX_HOUSEHOLD_FAMILYID_3301 on HOUSEHOLDSTAFFS_3301 (FAMILYID);
create index INDEXHHSORGCODECREATEDATE_3301 on HOUSEHOLDSTAFFS_3301 (ORGINTERNALCODE, CREATEDATE);
create index INDEXHOLDSTAFFORGCODE_3301 on HOUSEHOLDSTAFFS_3301 (ORGINTERNALCODE);
create index INDEX_HOLD_LOGOUT_3301 on HOUSEHOLDSTAFFS_3301 (LOGOUT);
create index INDEX_HOLD_MARKBIRTHDAY_3301 on HOUSEHOLDSTAFFS_3301 (MARKBIRTHDAY);
create index INDEX_HOLD_MARKGENDER_3301 on HOUSEHOLDSTAFFS_3301 (MARKGENDER);
create index IND_HOLDSF_IDORGICODE_3301 on HOUSEHOLDSTAFFS_3301 (ID, ORGINTERNALCODE);
create index IND_HOLDSTA_ORGID_3301 on HOUSEHOLDSTAFFS_3301 (ORGID);


