package com.tianque.aidsPopulations.dataConverter;

import com.tianque.core.datatransfer.DataType;
import com.tianque.domain.property.PropertyTypes;

public class SpecialGroupsContext {
	public static String[][] getAidspopulationsImportArrayNap() {
		String[][] excelColumArray = {
				{ "0", "name", "姓名", "", "", "true" },
				{ "1", "organization", "所属网格", DataType.DATA_TYPE_ORG, "",
						"true" },
				{ "2", "idCardNo", "身份证号码", "", "", "true" },
				{ "3", "infectway", "感染途径", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.INFECT_WAY, "true" },
				{ "4", "violationsofthelaw", "违法情况", DataType.DATA_TYPE_DICT,
						PropertyTypes.VIOLATIONSOFTHELAW, "true" },
				{ "5", "crimetype", "犯罪类型", DataType.DATA_TYPE_DICT,
						PropertyTypes.CRIMETYPE, "true" },
				{ "6", "receivedlevel", "收治机构所属层级", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.RECEIVED_LEVEL,
						"true" },
				{ "7", "receivedorganization", "收治机构", "", "", "true" },
				{ "8", "attentionExtent", "关注程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "9", "placeOfOrigin", "籍贯", "", "", "true" },
				{ "10", "contactWay", "联系方式", "", "", "true" } };
		return excelColumArray;
	}

	public static String[][] getAidspopulationsImportArraySap() {

		String[][] excelColumArray = {
				{ "0", "name", "姓名", "", "", "true" },
				{ "1", "organization", "所属网格", DataType.DATA_TYPE_ORG, "",
						"true" },
				{ "2", "gender", "性别", DataType.DATA_TYPE_DICT,
						PropertyTypes.GENDER, "true" },
				{ "3", "birthday", "出生日期", DataType.DATA_TYPE_DATE, "", "true" },
				{ "4", "idCardNo", "身份证号码", "", "", "true" },
				{ "5", "infectway", "感染途径", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.INFECT_WAY, "true" },
				{ "6", "violationsofthelaw", "违法情况", DataType.DATA_TYPE_DICT,
						PropertyTypes.VIOLATIONSOFTHELAW, "true" },
				{ "7", "crimetype", "犯罪类型", DataType.DATA_TYPE_DICT,
						PropertyTypes.CRIMETYPE, "true" },
				{ "8", "province", "省", "", "", "true" },
				{ "9", "city", "市", "", "", "true" },
				{ "10", "district", "县", "", "", "true" },
				{ "11", "isHaveHouse", "是否有固定地址", DataType.DATA_TYPE_BOOLEAN,
						"", "true" },
				{ "12", "houseCode", "房屋编号", "", "", "true" },
				{ "13", "noHouseReason", "无房原因", "", "", "true" },
				{ "14", "receivedorganization", "收治机构", "", "", "true" },
				{ "15", "receivedlevel", "收治机构所属层级", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.RECEIVED_LEVEL,
						"true" },
				{ "16", "nativePlaceAddress", "户籍详细地址", "", "", "true" },
				{ "17", "attentionExtent", "关注程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },

				{ "18", "otherAddress", "临时居所", "", "", "true" },
				{ "19", "usedName", "曾用名", "", "", "true" },
				{ "20", "nation", "民族", DataType.DATA_TYPE_DICT,
						PropertyTypes.NATION, "true" },
				{ "21", "politicalBackground", "政治面貌", DataType.DATA_TYPE_DICT,
						PropertyTypes.POLITICAL_BACKGROUND, "true" },
				{ "22", "schooling", "文化程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.SCHOOLING, "true" },
				{ "23", "email", "电子邮件", "", "", "true" },
				{ "24", "maritalState", "婚姻状况", DataType.DATA_TYPE_DICT,
						PropertyTypes.MARITAL_STATUS, "true" },
				{ "25", "bloodType", "血型", DataType.DATA_TYPE_DICT,
						PropertyTypes.BLOOD_TYPE, "true" },
				{ "26", "faith", "宗教信仰", DataType.DATA_TYPE_DICT,
						PropertyTypes.FAITH, "true" },
				{ "27", "career", "职业", DataType.DATA_TYPE_DICT,
						PropertyTypes.CAREER, "true" },
				{ "28", "telephone", "联系电话", "", "", "true" },
				{ "29", "mobileNumber", "联系手机", "", "", "true" },
				{ "30", "workUnit", "工作单位或就读学校", "", "", "true" },
				{ "31", "stature", "身高", DataType.DATA_TYPE_INTEGER, "", "true" },
				{ "32", "placeOfOrigin", "籍贯", "", "", "true" },
				{ "33", "contactWay", "联系方式", "", "", "true" },
				{ "34", "remark", "备注", "", "", "true" } };
		return excelColumArray;
	}

	public static String[][] getAidspopulationsImportArrayNdt() {
		String[][] excelColumArray = {
				{ "0", "name", "姓名", "", "", "true" },
				{ "1", "organization", "所属网格", DataType.DATA_TYPE_ORG, "",
						"true" },
				{ "2", "gender", "性别", DataType.DATA_TYPE_DICT,
						PropertyTypes.GENDER, "true" },
				{ "3", "birthday", "出生日期", DataType.DATA_TYPE_DATE, "", "true" },
				{ "4", "idCardNo", "身份证号码", "", "", "true" },
				{ "5", "infectway", "感染途径", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.INFECT_WAY, "true" },
				{ "6", "violationsofthelaw", "违法情况", DataType.DATA_TYPE_DICT,
						PropertyTypes.VIOLATIONSOFTHELAW, "true" },
				{ "7", "crimetype", "犯罪类型", DataType.DATA_TYPE_DICT,
						PropertyTypes.CRIMETYPE, "true" },
				{ "8", "province", "省", "", "", "true" },
				{ "9", "city", "市", "", "", "true" },
				{ "10", "district", "县", "", "", "true" },
				{ "11", "isHaveHouse", "是否有固定地址", DataType.DATA_TYPE_BOOLEAN,
						"", "true" },
				{ "12", "receivedorganization", "收治机构", "", "", "true" },
				{ "13", "receivedlevel", "收治机构所属层级", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.RECEIVED_LEVEL,
						"true" },
				{ "14", "nativePlaceAddress", "户籍详细地址", "", "", "true" },
				{ "15", "attentionExtent", "关注程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },

				{ "16", "otherAddress", "临时居所", "", "", "true" },
				{ "17", "usedName", "曾用名", "", "", "true" },
				{ "18", "nation", "民族", DataType.DATA_TYPE_DICT,
						PropertyTypes.NATION, "true" },
				{ "19", "politicalBackground", "政治面貌", DataType.DATA_TYPE_DICT,
						PropertyTypes.POLITICAL_BACKGROUND, "true" },
				{ "20", "schooling", "文化程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.SCHOOLING, "true" },
				{ "21", "email", "电子邮件", "", "", "true" },
				{ "22", "maritalState", "婚姻状况", DataType.DATA_TYPE_DICT,
						PropertyTypes.MARITAL_STATUS, "true" },
				{ "23", "bloodType", "血型", DataType.DATA_TYPE_DICT,
						PropertyTypes.BLOOD_TYPE, "true" },
				{ "24", "faith", "宗教信仰", DataType.DATA_TYPE_DICT,
						PropertyTypes.FAITH, "true" },
				{ "25", "career", "职业", DataType.DATA_TYPE_DICT,
						PropertyTypes.CAREER, "true" },
				{ "26", "telephone", "联系电话", "", "", "true" },
				{ "27", "mobileNumber", "联系手机", "", "", "true" },
				{ "28", "workUnit", "工作单位或就读学校", "", "", "true" },
				{ "29", "stature", "身高", DataType.DATA_TYPE_INTEGER, "", "true" },
				{ "30", "placeOfOrigin", "籍贯", "", "", "true" },
				{ "31", "contactWay", "联系方式", "", "", "true" },
				{ "32", "remark", "备注", "", "", "true" } };
		return excelColumArray;
	}

	public static String[][] getAidspopulationsImportArraySlf() {
		String[][] excelColumArray = {
				{ "0", "", "艾滋病人员清单", "", "", "true", "0", "34" },
				{ "0", "name", "姓名", "", "", "true" },
				{ "1", "organization", "所属网格", DataType.DATA_TYPE_ORG, "",
						"true" },
				{ "2", "gender", "性别", DataType.DATA_TYPE_DICT,
						PropertyTypes.GENDER, "true" },
				{ "3", "birthday", "出生日期", DataType.DATA_TYPE_DATE, "", "true" },
				{ "4", "idCardNo", "身份证号码", "", "", "true" },
				{ "5", "infectway", "感染途径", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.INFECT_WAY, "true" },
				{ "6", "violationsofthelaw", "违法情况", DataType.DATA_TYPE_DICT,
						PropertyTypes.VIOLATIONSOFTHELAW, "true" },
				{ "7", "crimetype", "犯罪类型", DataType.DATA_TYPE_DICT,
						PropertyTypes.CRIMETYPE, "true" },
				{ "8", "province", "省", "", "", "true" },
				{ "9", "city", "市", "", "", "true" },
				{ "10", "district", "县", "", "", "true" },
				{ "11", "isHaveHouse", "是否有固定地址", DataType.DATA_TYPE_BOOLEAN,
						"", "true" },
				{ "12", "receivedorganization", "收治机构", "", "", "true" },
				{ "13", "receivedlevel", "收治机构所属层级", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.RECEIVED_LEVEL,
						"true" },
				{ "14", "nativePlaceAddress", "户籍详细地址", "", "", "true" },
				{ "15", "attentionExtent", "关注程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },

				{ "16", "otherAddress", "临时居所", "", "", "true" },
				{ "17", "usedName", "曾用名", "", "", "true" },
				{ "18", "nation", "民族", DataType.DATA_TYPE_DICT,
						PropertyTypes.NATION, "true" },
				{ "19", "politicalBackground", "政治面貌", DataType.DATA_TYPE_DICT,
						PropertyTypes.POLITICAL_BACKGROUND, "true" },
				{ "20", "schooling", "文化程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.SCHOOLING, "true" },
				{ "21", "email", "电子邮件", "", "", "true" },
				{ "22", "maritalState", "婚姻状况", DataType.DATA_TYPE_DICT,
						PropertyTypes.MARITAL_STATUS, "true" },
				{ "23", "bloodType", "血型", DataType.DATA_TYPE_DICT,
						PropertyTypes.BLOOD_TYPE, "true" },
				{ "24", "faith", "宗教信仰", DataType.DATA_TYPE_DICT,
						PropertyTypes.FAITH, "true" },
				{ "25", "career", "职业", DataType.DATA_TYPE_DICT,
						PropertyTypes.CAREER, "true" },
				{ "26", "telephone", "联系电话", "", "", "true" },
				{ "27", "mobileNumber", "联系手机", "", "", "true" },
				{ "28", "workUnit", "工作单位或就读学校", "", "", "true" },
				{ "29", "stature", "身高", DataType.DATA_TYPE_INTEGER, "", "true" },

				{ "30", "hasServiceTeamMember", "有无服务成员",
						DataType.DATA_TYPE_COUNTS, "", "true" },
				{ "31", "lastRecordTime", "最新服务时间", DataType.DATA_TYPE_DATE,
						"", "true" }, { "32", "remark", "备注", "", "", "true" } };
		return excelColumArray;
	}

	public static String[][] getAidspopulationsImportArrayRla() {
		String[][] excelColumArray = {
				{ "0", "", "艾滋病人员清单", "", "", "true", "0", "36" },
				{ "0", "name", "姓名", "", "", "true" },
				{ "1", "organization", "所属网格", DataType.DATA_TYPE_ORG, "",
						"true" },
				{ "2", "gender", "性别", DataType.DATA_TYPE_DICT,
						PropertyTypes.GENDER, "true" },
				{ "3", "birthday", "出生日期", DataType.DATA_TYPE_DATE, "", "true" },
				{ "4", "idCardNo", "身份证号码", "", "", "true" },
				{ "5", "infectway", "感染途径", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.INFECT_WAY, "true" },
				{ "6", "violationsofthelaw", "违法情况", DataType.DATA_TYPE_DICT,
						PropertyTypes.VIOLATIONSOFTHELAW, "true" },
				{ "7", "crimetype", "犯罪类型", DataType.DATA_TYPE_DICT,
						PropertyTypes.CRIMETYPE, "true" },
				{ "8", "province", "省", "", "", "true" },
				{ "9", "city", "市", "", "", "true" },
				{ "10", "district", "县", "", "", "true" },
				{ "11", "isHaveHouse", "是否有固定地址", DataType.DATA_TYPE_BOOLEAN,
						"", "true" },
				{ "12", "houseCode", "房屋编号", "", "", "true" },
				{ "13", "noHouseReason", "无房原因", "", "", "true" },
				{ "14", "receivedorganization", "收治机构", "", "", "true" },
				{ "15", "receivedlevel", "收治机构所属层级", DataType.DATA_TYPE_DICT,
						com.tianque.constant.PropertyTypes.RECEIVED_LEVEL,
						"true" },
				{ "16", "nativePlaceAddress", "户籍详细地址", "", "", "true" },
				{ "17", "attentionExtent", "关注程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.ATTENTION_EXTENT, "true" },
				{ "18", "otherAddress", "临时居所", "", "", "true" },
				{ "19", "usedName", "曾用名", "", "", "true" },
				{ "20", "nation", "民族", DataType.DATA_TYPE_DICT,
						PropertyTypes.NATION, "true" },
				{ "21", "politicalBackground", "政治面貌", DataType.DATA_TYPE_DICT,
						PropertyTypes.POLITICAL_BACKGROUND, "true" },
				{ "22", "schooling", "文化程度", DataType.DATA_TYPE_DICT,
						PropertyTypes.SCHOOLING, "true" },
				{ "23", "email", "电子邮件", "", "", "true" },
				{ "24", "maritalState", "婚姻状况", DataType.DATA_TYPE_DICT,
						PropertyTypes.MARITAL_STATUS, "true" },
				{ "25", "bloodType", "血型", DataType.DATA_TYPE_DICT,
						PropertyTypes.BLOOD_TYPE, "true" },
				{ "26", "faith", "宗教信仰", DataType.DATA_TYPE_DICT,
						PropertyTypes.FAITH, "true" },
				{ "27", "career", "职业", DataType.DATA_TYPE_DICT,
						PropertyTypes.CAREER, "true" },
				{ "28", "telephone", "联系电话", "", "", "true" },
				{ "29", "mobileNumber", "联系手机", "", "", "true" },
				{ "30", "workUnit", "工作单位或就读学校", "", "", "true" },
				{ "31", "stature", "身高", DataType.DATA_TYPE_INTEGER, "", "true" },

				{ "32", "hasServiceTeamMember", "有无服务成员",
						DataType.DATA_TYPE_COUNTS, "", "true" },
				{ "33", "lastRecordTime", "最新服务时间", DataType.DATA_TYPE_DATE,
						"", "true" }, { "34", "remark", "备注", "", "", "true" } };
		return excelColumArray;
	}
}
